### PR TITLE
Printer: improve indentation

### PR DESCRIPTION
**Pull request by tobiasgrosser**
Before this patch we print nested regions as:

```
choco.ast.program() {}
 {
  choco.ast.call_expr() {
    choco.ast.id_expr() ["id" = "print"]
  }
 {
    choco.ast.binary_expr() ["op" = "+"]{
      choco.ast.binary_expr() ["op" = "+"]{
        choco.ast.literal() ["value" = !int<42>]
      }
 {
        choco.ast.literal() ["value" = !int<43>]
      }
 
    }
 {
      choco.ast.literal() ["value" = !int<44>]
    }
 
  }
 
}
```

after this patch we print them as:
```
choco.ast.program() {} {
  choco.ast.call_expr() {
    choco.ast.id_expr() ["id" = "print"]
  } {
    choco.ast.binary_expr() ["op" = "+"] {
      choco.ast.binary_expr() ["op" = "+"] {
        choco.ast.literal() ["value" = !int<42>]
      } {
        choco.ast.literal() ["value" = !int<43>]
      }
    } {
      choco.ast.literal() ["value" = !int<44>]
    }
  }
}

```

### CODE REVIEW

**Comment by Dinistro** [comment]
Now you just changed the way one compares the strings. Is the goal to actually fix the prints or just the comparison? 
Note that changing the prints might mess around with some filecheck tests so this would require fixing in this PR as well.

**Comment by tobiasgrosser** [comment]
Still working on it. I should hopefully get the failing test cases fixed soon.

**Comment by math-fehr** [comment]
Looks good to me.
Should we actually change `rewriter_test` to be whitespace independant?

**Comment by tobiasgrosser** [comment]
> Looks good to me. Should we actually change `rewriter_test` to be whitespace independant?

I think keeping it whitespace dependent is fine.

**Pull request merged**
