### PR TITLE
meta: Remove codeowners from experimental

### PR DESCRIPTION
**Pull request by AntonLydike**
I feel like we don't really want to have codeowners for experimental?

### CODE REVIEW

**Comment by math-fehr** [comment]
Why would you want to remove codeowners from experimental?
Someone has to be "in charge" of the experimental dialects and transformations, right?

**Comment by superlopuh** [comment]
I'd say we still want reviewers, just that the review standards should be different. My understanding of "code owners" is that they are responsible for the code, so people should only be added if its expected that they can be blamed when something goes wrong :)

**Comment by AntonLydike** [comment]
My train of thought was that for experimental PRs, we usually have a very limited scope of review, and the way it's currently set up, @math-fehr, @webmiche and @georgebisbas will be pinged for each PR into experimental there is. I feel that this is not actually what we want, right?

AFAIU we want to make sure the codeowners give their okay to the PR before it's merged. For me there are two options: either set up codeowners for each file in experimental, or make it so experimental doesn't partake in the codeowners thing.

If I misunderstood this we can def. keep having you be pinged for each experimental PR^^

**Comment by math-fehr** [comment]
I see!
First, I would say that we don't have to wait for all codeowners to give their approval on each PR, one should be enough.
Though, since we are still in the early stages of codeowners, I would say that we should treat codeowners as "suggestions" for naw.

Second, I think we should just attribute the experimental folders to the ones who owns them, no? We do have exactly the same problems in the `dialects` folder, where technically everyone should note which dialect they own.

The structure of our code as of right now is not that really suited for the codeowners file, to be honest. I'm personally wondering if we should not try to separate the repo a bit more, including tests and all.

**Comment by webmiche** [comment]
I agree with Mathieu here. I am getting tagged as a Codeowner on every PR, probably because of the testing folder. And that was probably not the goal when adding this.

Then again, I am not sure we should setup our folder structure for some convenience stuff. Github usually gives quite good suggestions of people who recently changed a file. Maybe that's just enough?

**Comment by AntonLydike** [comment]
Maybe we can also take a different approach to the codeowners file. Maybe we should strive for all owner assigments being correct instead of having each file assigned to at least one owner?

**Pull request closed without merging**
