### PR TITLE
builtin: Add ArrayAttr.__len__

### PR DESCRIPTION
**Pull request by AntonLydike**

### CODE REVIEW

**Review by PapyChacal — APPROVED** [review]
LGTM!

**Comment by superlopuh** [comment]
I'm not sure we really want this change, as the attribute itself is not iterable. It might just lead to more confusion about whether you're dealing with the attribute or the data it wraps.

**Comment by AntonLydike** [comment]
Okay, then make it iterable, I was playing with the idea of adding `__iter__` and `__getitem__` to it. I just didn't want to do it in this PR as I needed it for the stencil dialect (see #469)

**Comment by superlopuh** [comment]
At that point why not get the .data? Sugar comes at a cost, there's more API surface, and more confusion about what is what. `.data` is cheap and explicit

**Comment by AntonLydike** [comment]
Getting the `.data` actually triggers pyright, as it complains that `data` is a partially unknown type (`list[Unknown]`). I really don't want to have a variable assign + `cast` + `len`.

I think having these utility functions on the `ArrayAttr` is super helpful to write readable and expressive code without too much unnecessary shuffling and casting.

**Comment by AntonLydike** [comment]
I actually disagree with having a `attr.data_length`. Why should we re-invent the wheel? It's an array attribute, and it should have a length.

**Comment by superlopuh** [comment]
Because it's not the data, it's a wrapper around the data

**Comment by AntonLydike** [comment]
For a user, what's the difference? Does the user want to interact with the wrapper, or with the data?

We don't hide the wrapper with this, we just give the user a pythonic way to interact with it that's not a pain (due to pyright). Right?

For me, this just adds an easy public API that we can give the user, so the user doesn't have to worry about the underlying implementation. The user goes "so I have an array attribute here, what's the length of that?" and then he just calls `len(attr)` like he does everywhere else. For me this is a win.

**Pull request merged**
