### PR TITLE
dialects: (riscv) branch instructions and j are terminators

### PR DESCRIPTION
**Pull request by superlopuh**

### CODE REVIEW

**Review by compor — APPROVED** [review]

**Comment by compor** [comment]
LGTM,  I guess for `jal` and `jalr` we might need the `ReturnLike` trait.

**Comment by compor** [comment]
> I'm not sure they are returnlike, they're more like call expressions, not terminating

True, although it might be more conflated than this since `jalr` can be used to "jump back" to the "caller".
Something for later.

**Comment by superlopuh** [comment]
Ah yes didn't think of that, I guess we can be a bit more strict with our own lowering

**Comment by JosseVanDelm** [comment]
Hi, I'm having some difficulties with this PR:
* I'm not very familiar with basic blocks in SSACFG regions (forgive me for dumb questions!)
* The tests/diffs are difficult to read IMHO, with the interleaved filecheck comments. Can we maybe move away from inline comments and make a more block comment type of approach for the tests relating to basic blocks?
Or at least add one example that really focuses on CFG behaviour?
* I find it confusing that we have label-ops to jump to, if the `^bb0` labels from a multi-block region seem to serve the same purpose? What does the `LabelOp` model that the `^bb0` label doesn't?

**Review by AntonLydike — APPROVED** [review]
This I understand much better! LGTM!

**Comment by superlopuh** [comment]
Unfortunately we can't control the names of the basic blocks, otherwise they would be better to jump to indeed, modulo fixing the assembly printing to include block names. As far as I know, this is not something that MLIR supports, so we have to make do with an operation. Right now that operation is LabelOp, but maybe we can find a better way in the future.

**Comment by AntonLydike** [comment]
Hey @superlopuh, can you write a bit of an "how this should be used" doc? It's difficult for us to understand how exactly this should be used? Currently we're just guessing and that feels a bit disconnected/inefficient...

Some proper examples with a bit of background of why this is done in a specific way would be super helpful to steer the discussion and make the review process easier for us.

**Comment by superlopuh** [comment]
Who's we? I'm happy to add more documentation, but it's not clear to me what's not clear 😅. In MLIR, a successor of a block has to be in its parent region. Branch instructions in riscv jump to a different place in code, and don't come back to execute the instruction after the branch. Hence it makes sense for branch instructions to be terminators. I don't know of another way to implement this mechanism than the one in the PR. The filecheck files are examples of valid IR where each block in the region is terminated either by a ret, a j, or a branch instruction.

**Comment by superlopuh** [comment]
Closing this while we figure out how to satisfy the following constraints: riscv dialect should represent arbitrary riscv code, and us needing a way to reason about the stucture of the code when lowered from builtin

**Pull request closed without merging**
