### PR TITLE
dialects: Remove unused things from stencil dialect

### PR DESCRIPTION
**Pull request by meshtag**
This PR intends to clean things a bit and remove operations and attributes which are never used yet. We can chose to add them in the future as required, preferably along with tests ;)

### CODE REVIEW

**Review by PapyChacal — APPROVED** [review]
Thanks!

**Comment by mesham** [comment]
What's  the reasoning behind removing the DynAccessOp and CombineOp operations? I think these were popped in as they are in the stencil dialect but we are not using them currently I don't think in our work, so is the plan to remove these and then potentially add back in at some later date if they are needed in the future?

**Comment by georgebisbas** [comment]
Since it is still in experimental, I would avoid removing implemented stuff for the near future.
Is there an important reason we want them to be removed?

**Comment by meshtag** [comment]
> so is the plan to remove these and then potentially add back in at some later date if they are needed in the future?

Yes, that's what I thought. We can add them back as and when we require them, preferably with tests.

**Comment by tobiasgrosser** [comment]
> > > so is the plan to remove these and then potentially add back in at some later date if they are needed in the future?
> > 
> > 
> > Yes, that's what I thought. We can add them back as and when we require them, preferably with tests.
> 
> Ah right, not sure what other people think here - I would be tempted to suggest we keep these in the experimental stencil dialect, but the only way in which they will be promoted to the "production" stencil dialect is if somebody writes tests? That way we still have the operations if anybody needs them and the dialect is "complete" compared to the Open Earth Compiler, but this doesn't impact the maturity of the production dialect. Not sure what you think here?

My feeling is that the cost of maintaining an experimental stencil dialect and splitting them apart is higher than just dropping them for now and getting them back from the git history as they become necessary. If we drop them now, we can move on with the stencil dialect and focus our time on performance tuning.

**Review by mesham — APPROVED** [review]

**Comment by PapyChacal** [comment]
My cents on the topic: The operations removed in this PR are only implemented to be parsed and printed. There is no lowering for them currently.
I wouldn't really consider an operation _implemented_ if there's no way to actually lower and run it. So I'm for removing them for the moment, as a way to focus on the essential subset we currently rely on, get it to a mature state, then just augment the dialect from here on as desired or needed.

Having a clear base should only make it easier to properly implement the complete dialect!

**Review by PapyChacal — APPROVED** [review]

**Comment by PapyChacal** [comment]
@georgebisbas, are you agreeing with the removal of these operations after this discussion?

**Comment by georgebisbas** [comment]
> @georgebisbas, are you agreeing with the removal of these operations after this discussion?

Yes I am fine, thanks.

**Review by georgebisbas — APPROVED** [review]

**Pull request merged**
