### PR TITLE
dialects (arm): add custom syntax

### PR DESCRIPTION
**Pull request by emmau678**
Add custom ARM assembly syntax and generic roundtrip test to filecheck.
Note: stacked PR

### CODE REVIEW

**Review by compor — APPROVED** [review]

**Review by alexarice — APPROVED** [review]
I'd be happy to merge this into the parent PR and review them as one

**Comment by superlopuh** [comment]
@alexarice I don't get it, why not review them separately?

**Comment by alexarice** [comment]
I don't see the value of splitting this into 2 prs where the custom syntax is simple, and think it just creates more work in generating filecheck tests for the intermediate version without custom format.

**Comment by alexarice** [comment]
I admit though that here the work in splitting it had already been done so it was probably the wrong call. Sorry for that.

**Comment by superlopuh** [comment]
No worries, I see what you mean. We actually did a bit of work to make it as simple as it was in this PR, which you can infer by looking at the logic riscv.py file and what mechanism is used for the custom syntax there :)

**Pull request merged**
