### PR TITLE
backend: (riscv) emit assembler directives for functions

### PR DESCRIPTION
**Pull request by nazavode**
This PR emits all the directives needed to have function labels properly assembled (and hopefully linked) for our current default target (`rv32`). Please note that the emission of directives is done at the last possible moment where we still have structured info (e.g.: we still have `FuncOp` and its attributes like `sym_visibility`). @superlopuh I stashed your version on my laptop, if you think that is more appropriate I will close this and resume that one. Please let me know if something is needed on the `Toy` side.

**Stacked on top of #1526**

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
Very nice.

**Comment by superlopuh** [comment]
Is that expected to work, a new `.text` for each function? If so then this looks good to me. It looks like the Toy tests are passing so at least riscemu seems to handle it fine.

**Review by superlopuh — APPROVED** [review]

**Comment by nazavode** [comment]
> Is that expected to work, a new `.text` for each function? If so then this looks good to me. It looks like the Toy tests are passing so at least riscemu seems to handle it fine.

This is correct since assembler directives are flat, each section directive tells the assembler to switch in that mode and consider whatever comes next as part of the current section, until another directive makes it switch to another one. This makes sections as regions not really sound right to me (section closing is never seen by the assembler, so whatever we emit after that will still refer to the current section), but anyway it should work fine for now, modulo the linker script we have in the experiments repo. Checking for that when I have internet again.

**Review by AntonLydike — APPROVED** [review]
Looks good! Thanks for this!

**Pull request merged**
