### PR TITLE
tests: Remove redundant tests using the xDSL syntax

### PR DESCRIPTION
**Pull request by math-fehr**
These are the last tests that were in xDSL format in our repo.

### CODE REVIEW

**Comment by math-fehr** [comment]
So it seems that some types cannot be parsed back when given to MLIR.
I'll make an issue out of it for now, and removed the broken test I just added.

**Review by georgebisbas — CHANGES_REQUESTED** [review]
These are only dropped?

**Comment by math-fehr** [comment]
The `llvm` test is already in the repo, as well as the `ops` one, which was testing multiple operations, which are all tested in the repo as well.

**Review by webmiche — APPROVED** [review]

**Comment by math-fehr** [comment]
I just renamed the PR to reflect this

**Review by georgebisbas — APPROVED** [review]

**Review by superlopuh — APPROVED** [review]

**Pull request merged**
