### PR TITLE
[WIP] linalg to snitch

### PR DESCRIPTION
**Pull request by superlopuh**
WIP branch with changes to compile to snitch in Toy.

PRs left to open:
 - [x] pass function arguments to `xdsl-run`
 - [ ] implement interpreter for memref-stream and friends

### CODE REVIEW

**Comment by AntonLydike** [comment]
Is this a "review expected" kinda PR, or just meant as an overview. Because I'm added as a reviewer, but I see 1.5k lines added :smile:

**Comment by superlopuh** [comment]
It's just so everyone knows where to find the branch with the code that we used for the paper experiments, not a "review expected" PR, as you say :)

**Comment by superlopuh** [comment]
Now that the lowering is merged, I'll split out the useful parts of the prototyping/testing things I built in here into PRs, I'll keep this open until that's done (the splitting into tasks, not their merging), plan is to close this by the end of next week

**Comment by superlopuh** [comment]
With #2290, we can finally close this!

**Pull request closed without merging**
