### PR TITLE
dialects: Reverse array indexing for converting `stencil` to LLMLIR

### PR DESCRIPTION
**Pull request by tobiasgrosser**
This patch improves for me performance from 42.00 secs to 6.00 secs.

clang-17 -O3  -fopenmp 3d_diff.main.o 3d_diff.cpu.o 3d_diff.interop.o -o 3d_diff.out ./3d_diff.out
Timestamp is: 596620.54
Timestamp is: 596662.62
End of time is: 596662.62
Elapsed time is: 42.00 secs
python3 compare.py --name  3d_diff -d 300 300 300 -nt 300 Max error: 2.980232238769531e-07
Max abs value: 0.4215346574783325
rm 3d_diff.main.o 3d_diff.interop.o

clang-17 -O3  -fopenmp 3d_diff.main.o 3d_diff.cpu.o 3d_diff.interop.o -o 3d_diff.out ./3d_diff.out
Timestamp is: 596595.97
Timestamp is: 596602.00
End of time is: 596602.00
Elapsed time is: 6.00 secs
python3 compare.py --name  3d_diff -d 300 300 300 -nt 300 Max error: 2.980232238769531e-07
Max abs value: 0.4215346574783325
rm 3d_diff.main.o 3d_diff.interop.o

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
I just checked, and this works still. From my side this is ready to go.

**Review by superlopuh — APPROVED** [review]

**Review by georgebisbas — APPROVED** [review]
I am also happy with this. I have also seen as discussed some perf benefit, though much lower.

**Comment by meshtag** [comment]
AFAIU, dimensions were swapped for getting some perf benefits on GPU. ([Ref](https://github.com/xdslproject/xdsl/pull/602/files))
Are those still intact after this change?

**Comment by PapyChacal** [comment]
> AFAIU, dimensions were swapped for getting some perf benefits on GPU. ([Ref](https://github.com/xdslproject/xdsl/pull/602/files)) Are those still intact after this change?

I tried locally and thid didn't have significant impact on that side, because I have another major bottleneck for the generated code 5memory transfers). I'm guessing this should have some impact, but can be conditionally done for GPU if needed. Either way, priority is for the CPU performance first!

**Pull request merged**
