### PR TITLE
dialects: Fix LLVM variadic functions

### PR DESCRIPTION
**Pull request by kingiler**
Address #1244

### CODE REVIEW

**Comment by webmiche** [comment]
Does this solve the issue @gabrielrodcanal?

I think we should add an MLIR interoperation test as well. One that uses our API, generates a function and then feeds this into mlir-opt.  I think there is a test that does something similar, but I don't remember where. The frontend certainly runs something with python and then filechecks it. One could just add a roundtrip through mlir-opt there...

**Comment by gabrielrodcanal** [comment]
@webmiche Yes, this solves the issue!

**Review by AntonLydike — APPROVED** [review]

**Review by math-fehr — COMMENTED** [review]
👍

**Review by math-fehr — APPROVED** [review]

**Review by webmiche — APPROVED** [review]
Yes

> I think we should add an MLIR interoperation test as well

But if everyone else agrees, we can forget about that.

**Pull request merged**
