### PR TITLE
Irdl fix

### PR DESCRIPTION
**Pull request by math-fehr**
Fix bug related to verifiers.
The verifiers didn't worked prior to that for the manually written `verify_` functions.

### CODE REVIEW

**Comment by math-fehr** [comment]
I'm bundling another simple change with this!

**Comment by tobiasgrosser** [comment]
Hi @math-fehr, from the description and changes it is not clear why adding an argument to disable the verification of nested ops fixes a bug in costum verify functions. Also, it might help if you mention what this bug was initially.

**Comment by Dinistro** [comment]
@tobiasgrosser I guess the bug was caused by the wrong inheritance order and not in the other minor change. 

@math-fehr Is this related to https://github.com/xdslproject/xdsl/issues/18 or not?

**Comment by tobiasgrosser** [comment]
I see. Yes, I should have looked at the individual commit messages. This looks good to me then.

**Comment by math-fehr** [comment]
Yes, the bug was because of the inheritance order! Sorry, I added some other minor features to bundle everything quickly with xdsl 0.2.1
 
> @math-fehr Is this related to #18 or not?
No, I'll fix that later!

**Pull request merged**
