### PR TITLE
mlir printing and parsing fix

### PR DESCRIPTION
**Pull request by martin-luecke**
- fix mlir parsing of symbol_ref, e.g.
```
"some.mlirop"() {symbol = @some_symbol} : () -> ()
```

- fix mlir printing of tensors with unknown sizes
Now printed as `tensor<?x128xf32>` instead of `tensor<-1x128xf32>`.
This is required for reparsing with mlir-opt

### CODE REVIEW

**Review by math-fehr — CHANGES_REQUESTED** [review]
Looks good!
Can you just add two tests for the printing and parsing of these things?
Also, is the printing of the `FlatSymborRefAttr` implemented right now?

**Comment by martin-luecke** [comment]
@math-fehr In which test file do you suggest to put the tests? 
I see the other mlir printing/parsing tests are in `tests/filecheck/mlir-conversion/builtin_attrs.mlir'. 
I think that is not a good option as these tests are disabled when the C++ mlir python bindings are not found. (e.g. on my machine these tests are currently not run). The mlir printing/parsing does not require the mlir bindings so I think we should move all mlir printing/parsing tests to another location

**Comment by math-fehr** [comment]
> @math-fehr In which test file do you suggest to put the tests? I see the other mlir printing/parsing tests are in `tests/filecheck/mlir-conversion/builtin_attrs.mlir'. I think that is not a good option as these tests are disabled when the C++ mlir python bindings are not found. (e.g. on my machine these tests are currently not run). The mlir printing/parsing does not require the mlir bindings so I think we should move all mlir printing/parsing tests to another location

Right, I'll make a PR to fix this issue, which will start executing this file.
Otherwise, I would put it in `tests/filecheck/mlir-conversion/builtin_attrs.mlir` in the meantime, I fixed the file in my other PR.

**Comment by tobiasgrosser** [comment]
Hey @martin-luecke, is this PR still open? Is this sth we should tackle during the hackathon?

**Pull request merged**
