### PR TITLE
dialects: (riscv) Add rewrite pattern to optimize bitwise xor by zero

### PR DESCRIPTION
**Pull request by emmau678**
Add a rewrite pattern to the risv dialect for to optimise bitwise xor by zero (x^0 -> x)

### CODE REVIEW

**Review by superlopuh — APPROVED** [review]
LGTM! Could you please follow the checklist in the PR description before merging?

**Comment by emmau678** [comment]
> LGTM! Could you please follow the checklist in the PR description before merging?

Thanks, I have done that now. Should I self-merge this?

**Comment by superlopuh** [comment]
Yep! Thank you

**Comment by superlopuh** [comment]
Oh actually could you please remove the example from the getting started document?

**Comment by tobiasgrosser** [comment]
Congratulations to your first PR here!

**Pull request merged**
