### PR TITLE
docs: add onnx demo notebook

### PR DESCRIPTION
**Pull request by superlopuh**
Note that this is missing the interpreter part, since the bug is still there with the ABI calling convention not being respected when calling from the interpreter object directly.

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
This looks good to me. At some point we had the interpreter give us performance numbers. Did you drop them deliberately

**Comment by superlopuh** [comment]
Yes, it's because we currently have a bug in the interpreter. I wanted to merge the first part first, to not block on this issue to add a first real notebook:
#2122: interpreter: (riscv) external function call in riscv_func does not handle register dictionary in RiscvFunctions

**Comment by superlopuh** [comment]
The way it works in my local branch is by commenting some code that is needed for other functionality, and I'd like to resolve it properly, by setting the registers specified by the ABI

**Comment by tobiasgrosser** [comment]
Cool. Happy to merge it without the interpreter.

**Comment by superlopuh** [comment]
I'll interpret that as an "approve" :)

**Pull request merged**
