### PR TITLE
dialects: (llvm) Added pretty printing to llvm.mlir.constant

### PR DESCRIPTION
**Pull request by lfrenot**

### CODE REVIEW

**Review by superlopuh — COMMENTED** [review]
could you please install the pre-commit hook with `make precommit-install`, and run `make precommit` to format? Then I'd recommend running `make tests` to make sure the tests pass.

**Comment by tobiasgrosser** [comment]
Nice. Ready to merge?

**Review by tobiasgrosser — APPROVED** [review]

**Comment by lfrenot** [comment]
I think so
 @superlopuh do you have any comment?

**Comment by tobiasgrosser** [comment]
Let's merge this for now. @superlopuh, let us know if we missed sth.

**Comment by superlopuh** [comment]
LGTM!

**Pull request merged**
