### PR TITLE
core: surface original error when raising verification error

### PR DESCRIPTION
**Pull request by superlopuh**

### CODE REVIEW

**Review by adutilleul — APPROVED** [review]

**Review by webmiche — COMMENTED** [review]
Can you add a test showing what this does exactly? Looks like a good idea o/w :+1:

**Review by math-fehr — APPROVED** [review]
Nice!

**Comment by superlopuh** [comment]
```
>>> b = TestOp(operands=((),), result_types=((),), regions=((Return(),),))
>>> b.verify()
Traceback (most recent call last):
  File "/Users/sasha/Developer/xdslproject/xdsl/xdsl/ir/core.py", line 816, in verify
    self.verify_()
  File "/Users/sasha/Developer/xdslproject/xdsl/xdsl/irdl.py", line 1784, in verify_
    op_def.verify(self)
  File "/Users/sasha/Developer/xdslproject/xdsl/xdsl/irdl.py", line 1179, in verify
    trait.verify(op)
  File "/Users/sasha/Developer/xdslproject/xdsl/xdsl/traits.py", line 59, in verify
    raise VerifyException(
xdsl.utils.exceptions.VerifyException: 'func.return' expects parent op 'func.func'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sasha/Developer/xdslproject/xdsl/xdsl/ir/core.py", line 812, in verify
    region.verify()
  File "/Users/sasha/Developer/xdslproject/xdsl/xdsl/ir/core.py", line 1690, in verify
    block.verify()
  File "/Users/sasha/Developer/xdslproject/xdsl/xdsl/ir/core.py", line 1392, in verify
    operation.verify()
  File "/Users/sasha/Developer/xdslproject/xdsl/xdsl/ir/core.py", line 818, in verify
    self.emit_error(
  File "/Users/sasha/Developer/xdslproject/xdsl/xdsl/ir/core.py", line 989, in emit_error
    diagnostic.raise_exception(message, self, exception_type, underlying_error)
  File "/Users/sasha/Developer/xdslproject/xdsl/xdsl/utils/diagnostic.py", line 42, in raise_exception
    raise exception_type(message + "\n\n" + f.getvalue()) from underlying_error
xdsl.utils.exceptions.VerifyException: Operation does not verify: 'func.return' expects parent op 'func.func'

"test.op"() ({
  "func.return"() : () -> ()
  ^^^^^^^^^^^^^-----------------------------------------------------------
  | Operation does not verify: 'func.return' expects parent op 'func.func'
  ------------------------------------------------------------------------
}) : () -> ()


>>> 
```

**Comment by superlopuh** [comment]
As of right now, main only returns the second error and call stack, which is less useful

**Review by webmiche — APPROVED** [review]
Okay, thanks :+1:

**Pull request merged**
