### PR TITLE
tests: (minor) Remove helper class and adjust test dialect import

### PR DESCRIPTION
**Pull request by compor**
This PR performs a minor cleanup in tests (just `test_ir.py`) wrt changes in the `test` dialect from https://github.com/xdslproject/xdsl/pull/1305:

- Remove helper class `SuccessorOp` since `TestTermOp` accepts successors now
- Adjust `test` dialect import and use `test.TestOp` instead of `TestOp`

### CODE REVIEW

**Review by webmiche — APPROVED** [review]
Nice, still doing the Lords work, I see!

**Comment by compor** [comment]
> Nice, still doing the Lords work, I see!

just morning warmup ;)

**Review by tobiasgrosser — COMMENTED** [review]
I guess this makes sense to me.

**Review by math-fehr — APPROVED** [review]
<3

**Pull request merged**
