### PR TITLE
dialects: (func) Add custom syntax for func.return

### PR DESCRIPTION
**Pull request by AntonLydike**
This PR:

 - adds an `__init__` constructor for `func.Return`, deprecating the old one.
 - Adds custom print and parse as per MLIR docs

### CODE REVIEW

**Comment by AntonLydike** [comment]
The print and parse methods should be able to be lifted to `riscv.Return` and `scf.yield` and `stencil.return` I think. Maybe we should put them in a nice interface `ReturnOpLikePrinting`?

**Review by georgebisbas — APPROVED** [review]
NIce

**Review by webmiche — APPROVED** [review]
LGMT 👍

**Comment by webmiche** [comment]
> The print and parse methods should be able to be lifted to `riscv.Return` and `scf.yield` and `stencil.return` I think. Maybe we should put them in a nice interface `ReturnOpLikePrinting`?

It indeed seems that many dialects need such an operation to return controlflow back out of a region. Therefore, I think that would be a good idea 👍 

Not for this PR though, I really like the self-containedness of this one. Maybe open a starter issue?

**Pull request merged**
