### PR TITLE
tests: (riscv) migrate most riscv filecheck ops to custom syntax [NFC]

### PR DESCRIPTION
**Pull request by superlopuh**
Ripping the band-aid off.

### CODE REVIEW

**Comment by kingiler** [comment]
```shell
$ rg print-op-generic | rg riscv
tests/filecheck/dialects/riscv_func/riscv_func_ops.mlir:// RUN: xdsl-opt --print-op-generic %s | xdsl-opt | filecheck %s
```
This file should be using `XDSL_ROUNDTRIP`, right?

**Review by AntonLydike — APPROVED** [review]

**Review by tobiasgrosser — APPROVED** [review]
That looks amazing

**Review by nazavode — APPROVED** [review]
Custom syntax looks great!

**Review by adutilleul — APPROVED** [review]

**Comment by superlopuh** [comment]
@kingiler yep I'll have a go at the roundtripping files separately

**Pull request merged**
