### PR TITLE
Boolean attribute and parsing of this

### PR DESCRIPTION
**Pull request by mesham**
Simple addition to provide boolean attributes in builtin dialect which are useful for PSyclone work

### CODE REVIEW

**Review by webmiche — COMMENTED** [review]
LGTM. I feel that this could use a test case. Also, MLIR usually uses `i1`, so a 1-bit integer, for truth values. I am fine with adding booleans to our builtin, but maybe @math-fehr or @Dinistro have stronger opinions on this?

**Comment by tobiasgrosser** [comment]
I would suggest to minimize divergence with MLIR. Any idea if/why i1 would not work?

**Comment by math-fehr** [comment]
Sorry for the delay!

To me, it makes sense to add a boolean attribute. Not to use it with MLIR dialects, but with other dialects. So when we have a translation, we should not have any `bool` left.

Otherwise yes, could you just add some test cases for it (just for printing and parsing I guess)? So if we break something, we will directly see it from the CI.

**Comment by superlopuh** [comment]
What's the plan for this?

**Comment by math-fehr** [comment]
I talked with Nick, and this is not needed anymore!

**Pull request closed without merging**
