### PR TITLE
misc: make region blocks parameter variadic instead of iterable

### PR DESCRIPTION
**Pull request by superlopuh**
After playing with these APIs for a while, I feel that while it's best for block init to take a list, Region inits make sense to be variadic, since it's almost always a single block, especially when constructed explicitly.

### CODE REVIEW

**Review by math-fehr — COMMENTED** [review]
I'm not completely convinced that this design would be better that what we currently have.
This syntax is better when you create programs, since you know the number of block arguments.
However, when writing transformations, this syntax makes things worse, since you require the `*`.

I believe that while we should make the creation of programs nicer, we should be careful not making the  writing of transformations or generic code uglier.
So I'm not sure if we want this or not, but I'm happy to be wrong if people think this is the way to go.
I just feel really weird using a variadic here. To me, variadics are used when you know statically the number of them, but that's not really the case most of the time here?

Note also that we probably want to be consistent with other structures. If we do this here for `Region`, we probably want the same thing for `Block` (in another PR if we follow that route).

**Comment by superlopuh** [comment]
The Python variadics thing is a bit weird, since it's just minor syntactic sugar over a tuple. In this case, the implementation hasn't even changed, the way it works is by calling add block in a loop. So it's really about how we want this init API to look when creating a new Region. I made this init take a list to be consistent with Block, so I completely get that reasoning, and I don't think this is superior in any way other than the code, when looked at in isolation, looked nicer to me after the change.

**Comment by superlopuh** [comment]
Another alternative API that I think would work well is `__init__(blocks: Block | Sequence[Block])`, I'm happy to try that out if you'd like

**Comment by math-fehr** [comment]
Yeah I agree, this is just an API issue!

My problem is that I would prefer to avoid using variadics unless we have a good reason for it.
Here, I totally get that we often create a single block region, so I agree with accepting just a single block as parameter. It's just that whenever we do transformations, we have to unpack the tuple, which I'm not sure makes a lot of sense.

So yeah, I agree with the `Block | Sequence[Block]` way more, since we often just have a single block.

**Review by webmiche — COMMENTED** [review]
I agree that the code for sinlge regions looks a bit better, but as a non-Python programmer, I always need t think about variadics and what actually heppens. So to me, this adds another layer of complexity to think about when writing the code, which I find the hard part compared to writing `[ ]` essentially. I am slightly against this exact change therefore.

I think we can go the `Block | Sequence[Block]` route, but I feel we are getting into the territory again of making stuff harder to work with just for nicer syntax, which I don't like a lot. This approach does feel better than the current variadic approach to me though.

So in sum: I don't have a strong opinion, but I'd prefer the multi-types approach.

**Comment by PapyChacal** [comment]
> Another alternative API that I think would work well is `__init__(blocks: Block | Sequence[Block])`, I'm happy to try that out if you'd like

I'm not a fan of the variadic syntax either and that would have been my proposition :slightly_smiling_face:

**Comment by superlopuh** [comment]
Thank you for your inputs, I agree with all your feedback, the extra `[]` does make things more explicit, closing

**Comment by tobiasgrosser** [comment]
I liked the last proposal that Emilien also supported. Is this now also closed or are you planning to follow up on that one @superlopuh ?

**Comment by superlopuh** [comment]
I have another branch locally on top of this one, I'll open a PR for that first, and then we can compare the APIs with all the relevant bits of code that will depend on them. There's a few other API directions that a PR might not be the easiest format for discussions, but I'm happy to reopen this PR on top of those changes

**Pull request closed without merging**
