### PR TITLE
dialects: Add cf.assert

### PR DESCRIPTION
**Pull request by georgemitenkov**
This PR adds `assert` to `cf` dialect.

### CODE REVIEW

**Review by georgebisbas — CHANGES_REQUESTED** [review]
Try to only keep on in the title, add two labels

**Review by georgebisbas — APPROVED** [review]

**Review by superlopuh — APPROVED** [review]

**Review by webmiche — CHANGES_REQUESTED** [review]
I would prefer if you could split this PR into adding assert (with testcases) and then adding support in the frontend.

**Review by webmiche — COMMENTED** [review]
Could you add interoperation tests with MLIR? Afterward, I feel this is gtg.

**Comment by georgemitenkov** [comment]
@webmiche do you have an example where to do this?

**Comment by webmiche** [comment]
see [this test](https://github.com/xdslproject/xdsl/blob/main/tests/filecheck/mlir-conversion/with-mlir/ops.xdsl) for an example.

**Review by superlopuh — APPROVED** [review]

**Review by webmiche — APPROVED** [review]
LGTM now

**Pull request merged**
