### PR TITLE
dialects: (affine) freeze AffineMap

### PR DESCRIPTION
**Pull request by superlopuh**
This is kind of an RFC. It seems that most of the time we use affine maps as an immutable data structure, thought I'd leverage some python tools to enforce it. @Groverkss WDYT?

### CODE REVIEW

**Review by math-fehr — APPROVED** [review]
:+1:, making attributes pure is what we should aim for.
But I'll wait for @Groverkss as he may have needs to keep this mutable?

**Review by compor — APPROVED** [review]

**Review by Groverkss — CHANGES_REQUESTED** [review]
Blocking until we have a mature implementation of AffineMap.

**Comment by webmiche** [comment]
I guess we can close this PR for the time being, then. What do you think @superlopuh?

**Comment by superlopuh** [comment]
Chatted with Kunwar on Zulip, looks like he has upcoming changes, I'll rebase on those when they're in

**Pull request closed without merging**
