### PR TITLE
transformations: add call to `unblock_cmd_stream`

### PR DESCRIPTION
**Pull request by dk949**
This is needed at the end of the post-processing function to signal
program end.

### CODE REVIEW

**Review by n-io — COMMENTED** [review]
> This is needed at the end of the post-processing function to signal
program end.

This isn't quite the right fix, although for the right fix we're missing a pass. It should go at the end of the main function, and a good place for this is csl-stencil-to-csl-wrapper.

**Comment by dk949** [comment]
@n-io with the outer loop transformation you are working on, can I close this?

**Comment by n-io** [comment]
> @n-io with the outer loop transformation you are working on, can I close this?

I believe the cleanest way is to add it in the csl-stencil-to-csl-wrapper pass, simply at the end of the main func. I've opened #3198 for this

**Comment by dk949** [comment]
> > @n-io with the outer loop transformation you are working on, can I close this?
> 
> I believe the cleanest way is to add it in the csl-stencil-to-csl-wrapper pass, simply at the end of the main func. I've opened #3198 for this

Cool, I'll close this one then

**Pull request closed without merging**
