### PR TITLE
installation: Add xdsl-opt location to known paths

### PR DESCRIPTION
**Pull request by meshtag**
This PR intends to make `xdsl-opt` available from anywhere after running `pip install -e . `

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
Nice. Out of interest, could you share why the condition is necessary? Maybe including the reason for needing this in the commit message or in a comment

**Review by webmiche — CHANGES_REQUESTED** [review]
I think you should handle the CI thing differently. O/w LGTM

**Comment by meshtag** [comment]
The CI fails with this message: 
```
Err:1 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 clang amd64 1:10.0-50~exp1
  Could not connect to azure.archive.ubuntu.com:80 (52.161.185.214), connection timed out
Err:2 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 llvm-runtime amd64 1:10.0-50~exp1
  Unable to connect to azure.archive.ubuntu.com:http:
Err:3 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 llvm amd64 1:10.0-50~exp1
  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-defaults/clang_10.0-50~exp1_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (52.161.185.214), connection timed out
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-defaults/llvm-runtime_10.0-50~exp1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-defaults/llvm_10.0-50~exp1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

I am not really sure if this is due to the changes made by me. 

> Out of interest, could you share why the condition is necessary? Maybe including the reason for needing this in the commit message or in a comment

I tried naming [this commit](https://github.com/xdslproject/xdsl/pull/409/commits/460083362f07c74cd06824420f86007f113d4096) to make this more clear. I'll add a comment as well once the CI problem is solved.

**Comment by math-fehr** [comment]
I'm a bit confused, why do you need to `cd` into `xdsl`? At this point in the CI, aren't you already in the repo root?
Otherwise, this looks good to me to merge

**Comment by meshtag** [comment]
> I'm a bit confused, why do you need to `cd` into `xdsl`?

When I do not change the directory ([this commit](https://github.com/xdslproject/xdsl/pull/409/commits/8d01fbcbaf51cee38e66d4b20c17541d98b3e8a0)), it throws the following error: 
```
Traceback (most recent call last):
        File "/tmp/pip-build-env-0z03zere/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 140, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-0z03zere/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 330, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-0z03zere/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 261, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-0z03zere/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 288, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-0z03zere/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-0z03zere/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-0z03zere/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-0z03zere/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_scripts.py", line 57, in run
          self.copy_scripts()
        File "/tmp/pip-build-env-0z03zere/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_scripts.py", line 72, in copy_scripts
          self._copy_script(script, outfiles, updated_files)
        File "/tmp/pip-build-env-0z03zere/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_scripts.py", line 84, in _copy_script
          if not self.force and not newer(script, outfile):
        File "/tmp/pip-build-env-0z03zere/overlay/lib/python3.10/site-packages/setuptools/_distutils/dep_util.py", line 18, in newer
          raise DistutilsFileError("file '%s' does not exist" % os.path.abspath(source))
      distutils.errors.DistutilsFileError: file '/home/runner/work/xdsl/xdsl/xdsl/tools/xdsl-opt' does not exist
```

which is clearly a `path-not-found` error. I am not completely sure about the exact reason why we do not directly land in the root directory of the project before this point, but my guess is that we are supposed to be in the outer directory for properly setting up `mlir` build (steps involved are [this](https://github.com/xdslproject/xdsl/blob/33bf11e0d3488597d0865fc623a724e024f5b755/.github/workflows/ci-mlir.yml#L42) and [this](https://github.com/xdslproject/xdsl/blob/33bf11e0d3488597d0865fc623a724e024f5b755/.github/workflows/ci-mlir.yml#L68)).

**Comment by webmiche** [comment]
I decided to have the structure of the CI as follows:

xdsl (root)
-    xdsl (git clone)
-    llvm-project

Fundamentally, notice that the two git repos cannot be inside each other (firstly, git clone on the CI (silently) deletes stuff sometimes, if the folder is not completely empty, secondly pytest discovers to many tests, I think `pip install .` does weird stuff as well). This is the main reason why xdsl is not cloned directly into the root. We could probably also move the llvm-project up one layer and have git clone for xdsl in the root. Then we would just have to change directory in a bit more complex way for the llvm-project, but that is bearable. I am not sure there really is an advantage over the current version though, but maybe that's just best practice in CI design, I have no clue :sweat_smile:

**Comment by webmiche** [comment]
> The CI fails with this message:
> 
> ```
> Err:1 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 clang amd64 1:10.0-50~exp1
>   Could not connect to azure.archive.ubuntu.com:80 (52.161.185.214), connection timed out
> Err:2 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 llvm-runtime amd64 1:10.0-50~exp1
>   Unable to connect to azure.archive.ubuntu.com:http:
> Err:3 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 llvm amd64 1:10.0-50~exp1
>   Unable to connect to azure.archive.ubuntu.com:http:
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-defaults/clang_10.0-50~exp1_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (52.161.185.214), connection timed out
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-defaults/llvm-runtime_10.0-50~exp1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-defaults/llvm_10.0-50~exp1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```
> 
> I am not really sure if this is due to the changes made by me.

I think this was a weird github behavior, Your line was not even encountered before that failed. Also, it worked for the 3.11 CI, so... 

I retriggered the CI on that commit.

**Comment by webmiche** [comment]
I think you also needed to change `pip install -e xdsl[extras]` to `pip install -e .[extras]`, as you are now in the directory already.

**Comment by meshtag** [comment]
> I think you also needed to change pip install -e xdsl[extras] to pip install -e .[extras], as you are now in the directory already.

I think I did that ([Ref](https://github.com/meshtag/xdsl/blob/d950674dbb25bbc2152e96f7bedd644cd3a382a1/.github/workflows/ci-mlir.yml#L58)).

**Comment by math-fehr** [comment]
Oh okay, thanks for the explanation, I understand now that there are one more `xdsl` folder on top of the others ;)
It's good for merging for me, can you merge it @webmiche if this is good for you?

**Review by webmiche — APPROVED** [review]

**Comment by webmiche** [comment]
> > I think you also needed to change pip install -e xdsl[extras] to pip install -e .[extras], as you are now in the directory already.
> 
> I think I did that ([Ref](https://github.com/meshtag/xdsl/blob/d950674dbb25bbc2152e96f7bedd644cd3a382a1/.github/workflows/ci-mlir.yml#L58)).

Weird, not sure why it failed then. It works now, so I think we can merge it.

**Comment by webmiche** [comment]
> Oh okay, thanks for the explanation, I understand now that there are one more `xdsl` folder on top of the others ;)

Fun thing: there is actually three xdsl folders on top of each other. There is xdsl(root), xdsl(git clone), and than xdsl the folder in the repo xD

**Pull request merged**
