### PR TITLE
dialects: add jal, j, jalr + LabelAttr to riscv

### PR DESCRIPTION
**Pull request by superlopuh**
Also added region comments to riscv.py, quite useful for large files:

Screenshot 2023-05-05 at 10 49 43

### CODE REVIEW

**Review by AntonLydike — APPROVED** [review]
Nice!

**Comment by georgebisbas** [comment]
> Also added region comments to riscv.py, quite useful for large files:
> 
> Screenshot 2023-05-05 at 10 49 43

Try to copy-paste text than images!

**Comment by superlopuh** [comment]
> > Also added region comments to riscv.py, quite useful for large files:
> 
> > 
> 
> > Screenshot 2023-05-05 at 10 49 43
> 
> 
> 
> Try to copy-paste text than images!

Here I guess the message was more the line numbers on the left :)

**Review by nazavode — APPROVED** [review]

**Comment by tobiasgrosser** [comment]
This looks great.

**Pull request merged**
