### PR TITLE
tests: (math) Add constructor tests for Math dialect

### PR DESCRIPTION
**Pull request by ShaolunWang**
Adding constructor tests for math dialect

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
Instead of keeping a WIP PR open, maybe just add them in smaller PRs as they are ready?

**Comment by ShaolunWang** [comment]
@tobiasgrosser  Sure, I can change this pr's state/woring since the constructor tests are already done. I was waiting on furthur inputs on what kind of tests specifically are needed for this dialect, unfortunately there weren't any comments so far.

**Comment by superlopuh** [comment]
Without any questions to answer it's hard to know what's ready to comment on in draft PRs. It's worth either communicating via Zulip or writing a more informative description/comments on the diff itself to guide reviewers. It was not clear to me that you were hoping for feedback already.

**Comment by ShaolunWang** [comment]
>  It's worth either communicating via Zulip or writing a more informative description/comments on the diff itself to guide reviewers

I did post a message on zulip #framework channel under math dialect topic,  however there was no reply to it.

I'm happy to move this as the constructor test for math dialect, and make a new pr for adding more tests, if it's more suitable this way.

**Comment by AntonLydike** [comment]
Hey, cool work! I just wanted to drop by and say that this PR should probably have someone assigned to it who is responsible for merging it, if we want this merged. Also, I'll tag this as `testing`, since it's a PR touching tests

**Review by superlopuh — APPROVED** [review]

**Comment by superlopuh** [comment]
@ShaolunWang Sorry for the overhead, do you mind re-opening this and updating the code to the newer initialisers for the attributes? I merged without merging main and there's no way to reopen closed PRs...

**Pull request merged**
