### PR TITLE
tests: Add a test of cse to mlir lowered from stencil

### PR DESCRIPTION
**Pull request by georgebisbas**

### CODE REVIEW

**Comment by georgebisbas** [comment]
> Why do you want to test MLIR's CSE in the xDSL repository?

This is code lowered from the stencil dialect, so I think this would be helpful right? In case a lowering of stencil changes things it will also be caught here as well as in the other tests. You think it is useless?

**Comment by PapyChacal** [comment]
This new filecheck does not call the stencil lowerings, so it won't be affected by changes in the stencil lowerings.
It would only fail on changes of MLIR's `cse`, which I'm not sure we want to test.

It's an interesting point though, because we rely on MLIR to actually run this for now.

**Comment by meshtag** [comment]
> This new filecheck does not call the stencil lowerings, so it won't be affected by changes in the stencil lowerings.
> It would only fail on changes of MLIR's cse, which I'm not sure we want to test.
> 
> It's an interesting point though, because we rely on MLIR to actually run this for now.

I second that.

**Comment by georgebisbas** [comment]
So should I close this?

**Comment by webmiche** [comment]
I am in favor of closing this.

**Pull request closed without merging**
