### PR TITLE
mpi: Add mpi-info.c to dump mpi library info

### PR DESCRIPTION
**Pull request by AntonLydike**
I have this file here, which we need to generate the mpi library info for lowering MPI.

Does anyone know what's the best way to integrate this into xDSL so that we can so it automatically?

### CODE REVIEW

**Review by webmiche — COMMENTED** [review]
Can you get this info from within python? That would probably more cleanly integrate with the repo and your current thing. You could then have default values there and let users trigger regeneration through a flag or something...

**Comment by webmiche** [comment]
Depending on how forceful we want to be, we can always go with a `subprocess.run` based approach and than parse the output...

Just throwing in ideas...

**Comment by tobiasgrosser** [comment]
An alternative approach would be to not commit the .c file, but rather have a python function that emits the relevant C code. E.g. the MPI fields we want to list in the .c code are likely defined in our MPI bindings. I would assume that we could derive most this C-file from the code we already have. We can then add a comment and say running `python -m ...` will give the C file one needs to generate the right content.

**Comment by AntonLydike** [comment]
Yeah, I think an ideal solution would hide the raw C file and instead provide a flag to `xdsl-opt` that would then on-the-fly compile this and read the output back in.

I'm just not sure what's the best way to accomplish this right now... It's not critical for the paper, we have the values, but at some point we should integrate this into xdsl. That's why this is a draft. I'll probably not spend a lot of time on this until the deadline is over.

**Comment by webmiche** [comment]
I guess another maybe even cleaner approach would be to define some python bindings for this and introduce a new folder...

We might need something like this at some point anyhow, if we would want to speed up our rewriting dramatically, for example...

**Comment by webmiche** [comment]
The C file can also just be a string in python, which you compile through some sort of python bindings or just `subprocess run`...

**Comment by AntonLydike** [comment]
I think this PR is blocked by getting rewrite args in...

**Comment by AntonLydike** [comment]
Moved to issue, will come back to later

**Pull request closed without merging**
