### PR TITLE
Opt: move logic into separate file

### PR DESCRIPTION
**Pull request by Dinistro**
This draft PR refactors the xdsl-opt tool to make the class reusable for other projects based on xDSL, similar to MLIR's `MlirOptMain`. Furthermore, I adapted the `choco-opt` tool to show how this could be used: https://github.com/compiling-techniques/ChocoPyCompiler/pull/365 

If you have any suggestions or concerns, feel free to start a discussion here.

### CODE REVIEW

**Review by webmiche — APPROVED** [review]
LGTM. Some more documentation on this is particularly helpful I fell.

**Comment by Dinistro** [comment]
@math-fehr Do you think it makes sense to ship the `xdsl-opt` tool with the package, or should we move it into a separate tools directory that is not published?

**Review by math-fehr — APPROVED** [review]

**Comment by Dinistro** [comment]
> Yes, I think that's perfect! Maybe the only thing missing is a parser command line option to chose the format you want to parse. This is especially useful when parsing on stdin. 

At that point I wasn't sure about how to implement this. I think that using a parser option to override file extension specific parsing or for parsing from stdin might be the best approach. 
I'll add this option tomorrow. 

> Also, is there a reason why this is a draft PR? Are you missing something in the implementation?

Now that I think of it, not really^^

**Comment by math-fehr** [comment]
Looks good to me! We can merge it now if you want

**Pull request merged**
