### PR TITLE
dialects: Enhance stencil testing

### PR DESCRIPTION
**Pull request by georgebisbas**
Adds some filecheck tests on stencil dialect lowering

### CODE REVIEW

**Review by math-fehr — APPROVED** [review]
LGTM!

**Review by tobiasgrosser — COMMENTED** [review]
Would it make sense to make the heat_stencil kernels also non-symmetric?

**Comment by georgebisbas** [comment]
> Would it make sense to make the heat_stencil kernels also non-symmetric?

Tweaked the domain to be assymetric

**Comment by tobiasgrosser** [comment]
Cool. Ready to merge?

**Comment by tobiasgrosser** [comment]
Cool. Ready to merge?

**Comment by georgebisbas** [comment]
Yes we can, unless someone else has objections

**Pull request merged**
