### PR TITLE
core: IntegerType is an MLIRType

### PR DESCRIPTION
**Pull request by superlopuh**

### CODE REVIEW

**Review by georgebisbas — APPROVED** [review]

**Review by AntonLydike — APPROVED** [review]

**Comment by webmiche** [comment]
I saw Martin's comment on the other PR now. Is there a particular reason you need this for the PDL work?

**Comment by superlopuh** [comment]
Yep! The PDL example constrains a type to be of integer type, but it failed the check, as it was not a type. I've since discussed this with Mathieu, and xDSL doesn't have quite the same notion of types, so maybe it's superfluous, but this type is kind of from MLIR-land anyway, so this addition should be fine.

**Comment by math-fehr** [comment]
Yeah, it shouldn't change anything for parsing/printing, but it's better to be coherent with MLIR in that area!

**Comment by webmiche** [comment]
How abuut introducing a Type base class that inherits from Attribute? This can have the same printer implications as MLIRType currently. It seems people really want to think about types. With this, we could give them that while still reusing most of the code for Attribute...

**Comment by math-fehr** [comment]
> How abuut introducing a Type base class that inherits from Attribute? This can have the same printer implications as MLIRType currently. It seems people really want to think about types. With this, we could give them that while still reusing most of the code for Attribute...

Well, then what is the structure?
Both `ParametrizedAttr` and `Data` should be duplicated then?
I think that having an `MLIRType` as a marker makes  enough sense no?

**Comment by webmiche** [comment]
Hmm true...
I absolutely understand the MLIRType workaround, but do new users of xDSL understand it? And now that it seem that it is not only important for MLIRstyle printing, but for rewriting as well, shouldn't we build something that is more intuitive?
Maybe simply renaming MLIRType to Type might be enough?

**Comment by math-fehr** [comment]
Yeah, fine by me!

**Pull request merged**
