### PR TITLE
interactive: add test to count_number_of_ops

### PR DESCRIPTION
**Pull request by dshaaban01**

### CODE REVIEW

**Comment by superlopuh** [comment]
What's up with this PR? What happened? I thought the test was merged already

**Comment by dshaaban01** [comment]
> What's up with this PR? What happened? I thought the test was merged already

It was, the test that was already merged, tested the function on a moduleOp. And this test tests the function on a string which is parsed. to make sure it works. I thought twas fine?

**Comment by superlopuh** [comment]
Can you please wait for reviews before merging?

**Comment by dshaaban01** [comment]
> Can you please wait for reviews before merging?

Sorry, got excited. Won't happen again my bad!

**Pull request merged**
