### PR TITLE
Add tutorial for IRDL in the notebook

### PR DESCRIPTION
**Pull request by math-fehr**
I added a tutorial/documentation on how to create new operations, types, and attributes.
This also contain some quick fixes.
Tell me what you think!

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
It seems the include 'xdsl.printer' is not available in the latest pip release.

**Comment by math-fehr** [comment]
> It seems the include 'xdsl.printer' is not available in the latest pip release.

This should be fixed now

**Comment by tobiasgrosser** [comment]
This looks overall good. I would suggest to merge it and improve it incrementally as people start to use the notebook more and more.

**Comment by math-fehr** [comment]
Yes, though first I'll separate the IRDL version on another notebook, instead of having a huge notebook with all the features

**Pull request merged**
