### PR TITLE
core: add UnregisteredAttr

### PR DESCRIPTION
**Pull request by math-fehr**

### CODE REVIEW

**Comment by math-fehr** [comment]
This PR adds `UnregisteredAttr`, which is the equivalent for `UnregisteredOp` but for attributes and types.
Compared to MLIR, we merge both the `Attr` and the `Type` one, as we do for our attributes and types.
However, since we need to have consistent printing with MLIR, we encode the type in the attribute itself, and we add it as a parameter.

I'll add the parsing and printing in a separate PR, in order to make this PR smaller.

**Comment by math-fehr** [comment]
No clue why the CI is failing, either it is a GitHub bug, or something broke? (@PapyChacal )

**Comment by PapyChacal** [comment]
@math-fehr fixed, you need to rebase to get the green though, sorry about that

**Comment by math-fehr** [comment]
> @math-fehr fixed, you need to rebase to get the green though, sorry about that

Thanks a lot!
Don't be sorry for fixing things out of our control that quickly ;)

**Review by webmiche — COMMENTED** [review]
I am not 100% happy about how the whole is_type thing is handled atm. I think the integration with the parser would be interesting to see, as I feel you can actually pass the proper `is_type` there. That would help me to understand why you do it this way.

**Comment by math-fehr** [comment]
The constraints I have on this code is the following:
* I would like to have a single `UnregisteredAttr`, to avoid duplicating code between `UnregisteredAttr` and `UnregisteredType`.
* The parser knows if it is a type or an attribute, but the printer needs to know somehow which one it is.
* While I could just have the `is_type` constraint in the type itself, my reasonning is that having this as an attribute makes more sense, and makes it more generic.

If you have any idea on another design that respect this (or if you think one of these constraints does not make sense, like the first one), I'm happy to hear!
I'm fixing the parser and I"ll make a PR for it!

**Comment by math-fehr** [comment]
You can see in #632 how I handle parsing/printing.

**Comment by webmiche** [comment]
Okay, I think I am getting it more now. You also want to instantiate the same Attribute if you have the same name multiple times. That's why you need to preserve the info about its kind within the class rather than being able to pass it again each time. LGTM

**Review by superlopuh — APPROVED** [review]

**Pull request merged**
