### PR TITLE
core: (irdl) ParamAttrConstraint can infer recursively

### PR DESCRIPTION
**Pull request by superlopuh**
This seems to work, is there any reason not to do this?

Note: conflicts with #3456

### CODE REVIEW

**Review by alexarice — COMMENTED** [review]
I don't believe this is sound, `ParamAttrConstraint` only specifies the base class of the attribute and so could theoretically this could infer the wrong subclass?

**Comment by alexarice** [comment]
Note that I'm not sure if being able to capture subclasses is part of the intended semantics of `BaseAttr` and `ParamAttrConstraint`, and this might just be an artifact of using python's `isinstance`

**Comment by alexarice** [comment]
Could do an `is_runtime_final` check?

**Review by math-fehr — APPROVED** [review]
I think I either forgot to do this, or at the time `is_runtime_final` didn't exist yet!
So yeah that looks good to me!

**Comment by math-fehr** [comment]
> A similar question to this is whether a `BaseAttr` applied to a type with no parameters should be inferable

Yes it should! What we could do is write an optimization to "convert" a `BaseAttr` with a singleton type to an `EqType`, that would also work!

**Pull request merged**
