### PR TITLE
interactive: toggle condense/uncondense button (4/7)

### PR DESCRIPTION
**Pull request by dshaaban01**
Added uncondense button functionality.

image

### CODE REVIEW

**Comment by superlopuh** [comment]
Why two buttons? Could you make the condense button say "Uncondense" when it's condensed? There's an example of how to do this with tcss and hiding/showing buttons based on a boolean state in the tutorial

**Review by compor — COMMENTED** [review]
A "toggle" button would work best as @superlopuh suggested

**Comment by superlopuh** [comment]
The button code looks great but it feels like there might be some unrelated code in here also?

**Comment by superlopuh** [comment]
I don't get where those errors are introduced, seems like something's off with the stacked branches

**Pull request merged**
