### PR TITLE
transformations: (lift-arith-to-linalg) Add generic FMA

### PR DESCRIPTION
**Pull request by n-io**
Adds the option to lift arith to generic fused multiply-add ops, with various flags to control behaviour.

### CODE REVIEW

**Review by superlopuh — COMMENTED** [review]
This feels like it's doing two things at the same time, and breaking the composability of rewrites. Could the ops be fused by a separate pass?

**Comment by n-io** [comment]
The behaviour can be switched on and off by a flag, but doing this in a separate pass is (mildly) more complicated, as the regions contain `arith.addf` and `arith.mulf` which the pass as-is would attempt to translate.

**Comment by AntonLydike** [comment]
I agree with Sasha here, lifting arith to linalg is one thing, but fusing operations together is a different thing entirely

**Comment by n-io** [comment]
Closing in favour of doing this in a separate pass.

**Pull request closed without merging**
