### PR TITLE
core: replace Rewriter.insert_op_at_pos with start/end

### PR DESCRIPTION
**Pull request by superlopuh**

### CODE REVIEW

**Review by georgebisbas — APPROVED** [review]

**Review by math-fehr — APPROVED** [review]
👍

**Comment by mesham** [comment]
What's the reason behind removing this? I have found it useful to have this, but I guess the argument is to use a rewriter instead and insert_op_before method as part of that?

**Comment by superlopuh** [comment]
The `list` implementation of `Block.ops` has been replaced with a linked list, so getting the index is now O(n) where n is the number of ops in the block, and before/after is constant time. We're removing the index-based functions to encourage the more efficient function

**Comment by superlopuh** [comment]
I think the rewriter is also generally the better thing to use, since it keeps track of additions/removals for iteration during a rewrite

**Pull request merged**
