### PR TITLE
documentation: (Toy) add instruction on how to jit Toy using lli

### PR DESCRIPTION
**Pull request by superlopuh**
Now that Toy lowers to print_format, we can compile it to LLVM, leveraging the printf flow added in #1142 .

### CODE REVIEW

**Comment by JosseVanDelm** [comment]
Why not use `mlir-cpu-runner` instead of `mlir-translate | lli`?

**Comment by superlopuh** [comment]
Because I found out about this via this PR :)

**Review by webmiche — APPROVED** [review]
:heart_eyes:

**Comment by superlopuh** [comment]
```
!python -m toy examples/interpret.toy --emit=scf --ir | xdsl-opt -p printf-to-llvm | mlir-opt --test-lower-to-llvm | mlir-cpu-runner
Error: only single f32 function result supported
```
Not sure what's going wrong here...

**Review by compor — APPROVED** [review]

**Comment by JosseVanDelm** [comment]
@superlopuh I think you have to use `mlir-cpu-runner --entry-point-result=void`:
```
  --entry-point-result=<f32 | i32 | i64 | void>      - Textual description of the function type to be called
```

**Pull request merged**
