### PR TITLE
dialects: Update dmp.swap

### PR DESCRIPTION
**Pull request by PapyChacal**
Give it a proper signature for value-semantics and reference-semantics.
It now needs to return values if taking values in, and need only an in-place operand if reference-semantics.

Update the distribution pass, to replace the loaded values by the swapped values, building a consistent def-use chain.

### CODE REVIEW

**Comment by PapyChacal** [comment]
@n-io I'm completely lost with regards to what's breaking where in your `stencil-to-csl-stencil` pass. Could you please have a look?

**Comment by PapyChacal** [comment]
Thanks @n-io !

**Review by n-io — COMMENTED** [review]
Please could you add filechecks for both value and reference semantics if not already present?

**Comment by PapyChacal** [comment]
> Please could you add filechecks for both value and reference semantics if not already present?

Already done in `tests/filecheck/dialects/dmp/canonicalize.mlir` and `tests/filecheck/dialects/dmp/ops.mlir` ?

**Comment by n-io** [comment]
> > Please could you add filechecks for both value and reference semantics if not already present?
> 
> Already done in `tests/filecheck/dialects/dmp/canonicalize.mlir` and `tests/filecheck/dialects/dmp/ops.mlir` ?

Yes, but it would benefit from also being in the transformation (this PR has a transformation label).

**Review by n-io — APPROVED** [review]

**Comment by PapyChacal** [comment]
> > > Please could you add filechecks for both value and reference semantics if not already present?
> > 
> > 
> > Already done in `tests/filecheck/dialects/dmp/canonicalize.mlir` and `tests/filecheck/dialects/dmp/ops.mlir` ?
> 
> Yes, but it would benefit from also being in the transformation (this PR has a transformation label).



> > > Please could you add filechecks for both value and reference semantics if not already present?
> > 
> > 
> > Already done in `tests/filecheck/dialects/dmp/canonicalize.mlir` and `tests/filecheck/dialects/dmp/ops.mlir` ?
> 
> Yes, but it would benefit from also being in the transformation (this PR has a transformation label).

For the PR's record, also done in `tests/filecheck/transforms/distribute-stencil.mlir` and `tests/filecheck/transforms/stencil-to-csl-stencil.mlir`

**Pull request merged**
