### PR TITLE
core: Register passes lazily

### PR DESCRIPTION
**Pull request by math-fehr**
This means we don't load a pass file unless we are using it.
This will save us a lot of startup time when we do the same for operations.

This already put us from 500ms (!!) to 400ms

### CODE REVIEW

**Comment by superlopuh** [comment]
Looks good! Have you solved the trace breaking?

**Comment by math-fehr** [comment]
> Looks good! Have you solved the trace breaking?

What trace breaking? Do you have an example?

**Comment by superlopuh** [comment]
If you remember the last time I tried this, I ran `xdslopt` with and without this diff, and for some reason tracing broke when the passes were made lazy. I'll try to reproduce this now

**Comment by superlopuh** [comment]
Seems to work fine now, I got to traces, and can confirm that it's 100 ms faster

**Review by superlopuh — APPROVED** [review]

**Comment by superlopuh** [comment]
Ah also I think I got confused with the lazy dialect loading

**Comment by math-fehr** [comment]
Hmm, I'm wondering if what you saw was actually a "compile-time" error triggered when loading a dialect file?
But nice!

**Comment by math-fehr** [comment]
Couldn't reproduce it as well, so I guess that's fine!

**Pull request merged**
