### PR TITLE
backend: (riscv) Add an initial lowering from snitch_runtime to snitch

### PR DESCRIPTION
**Pull request by AntonLydike**
Add lowering from `snitch_runtime` to `snitch`.

### CODE REVIEW

**Comment by superlopuh** [comment]
I have a feeling that the reference version of the snitch runtime linked in the comment is not the one that we use in the verilator. Let's wait for Federico to confirm.

**Comment by AntonLydike** [comment]
@superlopuh How do we want to continue with this? Add tests and merge or close?

**Comment by superlopuh** [comment]
I think we want to skip the snitch runtime, in the WIP branch I copy/pasted these changes to go directly from snitch stream to snitch. I'll open that quickly and then we can discuss plans?

**Comment by compor** [comment]
Closing in favour of #1718

**Pull request closed without merging**
