### PR TITLE
docs: drop star imports

### PR DESCRIPTION
**Pull request by georgebisbas**
@math-fehr is there any reason why we use star imports in xdsl?

https://www.geeksforgeeks.org/why-import-star-in-python-is-a-bad-idea/

Let me know your thoughts.

### CODE REVIEW

**Comment by math-fehr** [comment]
Sorry for the delay!
Yes, I didn't know better when I started this, so this is greatly appreciated!

**Comment by math-fehr** [comment]
I think we can merge it once #131 is merged?

**Review by math-fehr — APPROVED** [review]

**Comment by georgebisbas** [comment]
I think it looks much cleaner now and will help towards better, more structured development later.

There are two places in the code in irdl.py
where:

```
    # So we have a circular dependency that we solve by importing in this function.
```
Any idea on how to resolve them?

**Comment by math-fehr** [comment]
> I think it looks much cleaner now and will help towards better, more structured development later.
> 
> There are two places in the code in irdl.py where:
> 
> ```
>     # So we have a circular dependency that we solve by importing in this function.
> ```
> 
> Any idea on how to resolve them?

I dont' think we can't do anything about it. It seems to be the "standard" way of handling circular dependencies.

**Comment by georgebisbas** [comment]
@math-fehr I rebase on top of current master

**Comment by math-fehr** [comment]
Perfect, seems good to me, I'll merge it before we get merge conflcts from other PRs ;)

**Pull request merged**
