### PR TITLE
CI: Count irdl-to-pyrdl in coverage stats.

### PR DESCRIPTION
**Pull request by PapyChacal**
@math-fehr  (Intended to be actually merged in your PR if it works as intended)

### CODE REVIEW

**Comment by math-fehr** [comment]
Ohhh, perfect!
I haven't added a script there for `irdl-to-pyrdl`, as I wasn't sure if we needed it since we have the installation.
Should I add it?

**Comment by PapyChacal** [comment]
> Ohhh, perfect! I haven't added a script there for `irdl-to-pyrdl`, as I wasn't sure if we needed it since we have the installation. Should I add it?

Let's find out :shrug: I'm not sure anywore what purpose xdsl/tools/xdsl-opt (not xdsl-opt.py) serves TBH? :thinking:

**Comment by math-fehr** [comment]
I don't know either :/

**Comment by PapyChacal** [comment]
> I don't know either :/

Tried locally and this should be alright, just added the `.py` in the lit substitution!

**Comment by PapyChacal** [comment]
@math-fehr 
https://app.codecov.io/gh/xdslproject/xdsl/pull/1108/blob/xdsl/dialects/irdl/irdl_to_pyrdl.py
Got something working, check the diff if anything bugs you still :wink:

**Pull request merged**
