### PR TITLE
core: correct `__str__`/`__repr__` usage in ParseError

### PR DESCRIPTION
**Pull request by PapyChacal**
Hey, I'm trying to have fun with MLIROptPass as part of our Python DSL integration.

Sadly, when chaining a ParserError (such as when MLIROptPass fails because xDSL can't parse back MLIR's output), it looks like this:
```
>       raise ParseError(at_position, msg)
E       xdsl.utils.exceptions.ParseError: (Span[1151:1154](text='ptr'), 'type expected')
```
Which isn't very helpful.
This PR offers to force it to display nicely in this case too, yielding instead:
```
    raise ParseError(at_position, msg)
xdsl.utils.exceptions.ParseError: <unknown>:23:52
    %19 = "llvm.mlir.undef"() : () -> !llvm.struct<(ptr, ptr, i64, array<3 x i64>, array<3 x i64>)>
                                                    ^^^
                                                    type expected
```
Which is more actionnable.

I'm not sure overriding `__str__` is the only nor the best solution though. WDYT?

### CODE REVIEW

**Review by webmiche — COMMENTED** [review]
Hmm, I think I would prefer to handle this special case in the MLIROpt pass itself rather than changing core classes like the ParseError. I would assume that the MLIROpt pass, as a pass that runs something on the cmdline and reparses and stuff, is more of a unicorn than a normal pass.

Also, I am surprised that no other tests actually fail, but I guess we did not test parsing errors very thoroughly :thinking:

**Comment by webmiche** [comment]
Also, connecting `__repr__` and `__str__` in this way feels not very "pythonic" given that the two usually have different focus (AFAIU).

**Comment by PapyChacal** [comment]
> Hmm, I think I would prefer to handle this special case in the MLIROpt pass itself rather than changing core classes like the ParseError. I would assume that the MLIROpt pass, as a pass that runs something on the cmdline and reparses and stuff, is more of a unicorn than a normal pass.
> 
> Also, I am surprised that no other tests actually fail, but I guess we did not test parsing errors very thoroughly 🤔

Makes sense, I'm okay with that as it's enough for my usecase!
Though, the failing GUI test made me think it might help there too, hence proposing the core change! But I'll move this to MLIROptPass first :slightly_smiling_face:

**Comment by PapyChacal** [comment]
Mh; I'm actually not sure how to do this without going far with the exception handling.
It seems that using `__str__` is just the default behaviour of chained exceptions.
Also, doesn't this user-friendly make more sense as `__str__` than `__repr__`, in the Pythonic mindset?

**Comment by AntonLydike** [comment]
I guess overwriting `__str__` is the easy way out, but eventually we would want a global exception handler in xdsl-opt-main or something so that we can catch and pretty print these errors (and verification errors, etc.)

For now I'm very happy with this change, I think it's overall positive.

**Comment by PapyChacal** [comment]
So I just pushed something else, basically just replacing the `__repr__` by the `__str__`.
This is the intended usage of the API AFAIU? `__str__` is the nice, user-friendly representation, and `__repr__` is the strict, dataclass-generated, evaluatable representation.
WDYT @webmiche?

**Comment by PapyChacal** [comment]
> I guess overwriting `__str__` is the easy way out, but eventually we would want a global exception handler in xdsl-opt-main or something so that we can catch and pretty print these errors (and verification errors, etc.)
> 
> For now I'm very happy with this change, I think it's overall positive.



> I guess overwriting `__str__` is the easy way out, but eventually we would want a global exception handler in xdsl-opt-main or something so that we can catch and pretty print these errors (and verification errors, etc.)
> 
> For now I'm very happy with this change, I think it's overall positive.

I think that's just the role of `__str__` though? Why would we need to reimplement an exception handler for pretty printing?

**Comment by math-fehr** [comment]
Yeah, looks to me that this should have always been __str__ instead of __repr__!

**Review by webmiche — APPROVED** [review]
Yes, I agree. Thinking about it more, this should have always been `__str__` :+1:

**Review by dshaaban01 — COMMENTED** [review]
Look's great! Thank you for adding this!

**Pull request merged**
