### PR TITLE
builtin: Improve VectorType.from_type_and_list() constructor

### PR DESCRIPTION
**Pull request by meshtag**
This PR intends to modify the `VectorType.from_type_and_list()` constructor in accordance with [this](https://github.com/xdslproject/xdsl/pull/300#discussion_r1066818410) discussion.

### CODE REVIEW

**Review by georgebisbas — APPROVED** [review]

**Review by webmiche — APPROVED** [review]
I am actually quite surprised how huge the change in to notebook is. Could you try to find a way to only include the change on the actual constructor (which is just one line AFAIU)? If this happens to be more complex then expected, I am fine with merging anyhow :)

**Review by math-fehr — APPROVED** [review]
Looks good to me, besides the notebook which has a huge change (seems indentation-related)

**Comment by meshtag** [comment]
The large diff was due to the formatting indentation introduced by `yapf` when I tried to format `irdl.ipynb`. I reverted it, I don't think I can further reduce the diff size.

**Comment by webmiche** [comment]
I aw guessing that you are using a different jupyter version as I was when adding the notebook. That version seems to have stored metadata a bit differently. I managed to reduce the size by quite a bit again. Let's wait for the CI to finish, then we can merge.

**Comment by webmiche** [comment]
And there was a change in printing Attributes at some point, which was not yet reflected in the notebooks...

**Comment by meshtag** [comment]
> I aw guessing that you are using a different jupyter version as I was when adding the notebook. That version seems to have stored metadata a bit differently.

Ahh, I see. Do you think we should put this information somewhere in the readme? Imo, this is not a strict requirement per se, but would help to keep the size of code base from unnecessarily increasing. 

> And there was a change in printing Attributes at some point, which was not yet reflected in the notebooks...

Should this be handled in this PR itself?

**Comment by meshtag** [comment]
For consistency, should we modify corresponding `memref` [constructor](https://github.com/xdslproject/xdsl/blob/1887f978d874c3819287483c4d9aa45c00905f56/xdsl/dialects/memref.py#L125) as well?

**Comment by meshtag** [comment]
> For consistency, should we modify corresponding memref [constructor](https://github.com/xdslproject/xdsl/blob/1887f978d874c3819287483c4d9aa45c00905f56/xdsl/dialects/memref.py#L125) as well?

Gentle ping @math-fehr @webmiche @georgebisbas

**Comment by math-fehr** [comment]
Sorry, I missed this message!
Yes, I think we should try to be consistent there!

**Comment by webmiche** [comment]
I guess constructors overall are an issue that we should think about more...

**Pull request merged**
