### PR TITLE
misc: allow passing single block to Region init

### PR DESCRIPTION
**Pull request by superlopuh**
This is a minor syntactic sugar for Region init, a kind of reboot of a previous PR. The proposed way to spell a single block region is `Region(Block())`, a multi-block region is `Region([b0, b1])`.

The question is whether this is nice enough sugar to make it in.

### CODE REVIEW

**Review by PapyChacal — APPROVED** [review]
I find this sugar very nice enough indeed :)

**Review by math-fehr — APPROVED** [review]
:+1:

**Review by webmiche — APPROVED** [review]
This sugar is sweet enough for me :+1:

**Comment by tobiasgrosser** [comment]
I like it. xDSL becomes very beautiful these days.

**Pull request merged**
