### PR TITLE
transformations: application of PDL patterns from source

### PR DESCRIPTION
**Pull request by qaco**
transformations: application of PDL patterns from source

### CODE REVIEW

**Review by superlopuh — COMMENTED** [review]
Why not reuse the logic in `PDLRewritePattern`?

**Comment by qaco** [comment]
> Why not reuse the logic in `PDLRewritePattern`?

In some cases, such as in the test I provide, you need to match several operations with the same ```PDLMatcher``` before rewrite. For the moment, however, ```PDLRewritePattern``` only matches a single operation.

**Comment by qaco** [comment]
> Oh, interesting. I'm not sure that I understand the exact limitation, but I feel that this might be worth putting somewhere closer to the rewrite pattern anyway? The thing I was suggesting initially was to just creating `PDLRewritePatterns` in a loop, and stopping when nothing matched in the loop at all. This should already work, and if it doesn't then wemight want to fix it in the interpreter implementation file, as opposed to this helper that should ideally be relatively minimal.

It may happen that the matching of an op2 operation depends on the matching of a previous op1 operation, for example when the result of op1 must be an argument of op2.

I understand the point. I thought that this implementation of ```PDLRewritePattern``` was required for some specialized usage. So, this change can be done in two ways:

 requires to feed the ```PDLRewritePattern``` with pairs (patternop,containerop) instead of (rewriteop,innerop). Are you ok with this change ?

**Comment by superlopuh** [comment]
Hmm, but the matching already handles this? It matches starting from the root op, and can go up an arbitrary number of operations.

**Comment by qaco** [comment]
> Hmm, but the matching already handles this? It matches starting from the root op, and can go up an arbitrary number of operations.

I must be missing the point. I have no change with the following:
```
for pdl_op in pattern.walk():
    if isinstance(pdl_op, pdl.RewriteOp):
        stream = StringIO()
        pattern_rewriter = PatternRewriter(payload_module)
        pdl_rewrite_pattern = PDLRewritePattern(pdl_op,ctx,stream)
        pdl_rewrite_pattern.match_and_rewrite(payload_module,pattern_rewriter)
```

I guess I misunderstand how ```PDLRewritePattern``` works. I'll dig tomorrow.

**Comment by qaco** [comment]
> > Hmm, but the matching already handles this? It matches starting from the root op, and can go up an arbitrary number of operations.
> 
> I must be missing the point. I have no change with the following:
> 
> ```
> for pdl_op in pattern.walk():
>     if isinstance(pdl_op, pdl.RewriteOp):
>         stream = StringIO()
>         pattern_rewriter = PatternRewriter(payload_module)
>         pdl_rewrite_pattern = PDLRewritePattern(pdl_op,ctx,stream)
>         pdl_rewrite_pattern.match_and_rewrite(payload_module,pattern_rewriter)
> ```
> 
> I guess I misunderstand how `PDLRewritePattern` works. I'll dig tomorrow.



> Hmm, but the matching already handles this? It matches starting from the root op, and can go up an arbitrary number of operations.

It is corrected now. Thank you for your careful advices.

**Review by superlopuh — COMMENTED** [review]
Nice! Although I think it might be possible to get the same result via a greedy pattern applier, and without modifying the existing pdl pattern. The way I see this working is by first getting all the pdl pattern ops, creating an xDSL pattern for each op, and then putting them in a greedy pattern, like a normal pass would. Could you please try this? Hopefully should also work

**Comment by qaco** [comment]
> Nice! Although I think it might be possible to get the same result via a greedy pattern applier, and without modifying the existing pdl pattern. The way I see this working is by first getting all the pdl pattern ops, creating an xDSL pattern for each op, and then putting them in a greedy pattern, like a normal pass would. Could you please try this? Hopefully should also work

It's done and it works !

**Pull request closed without merging**
