### PR TITLE
Fehr/fix parser parametric attr

### LINKED ISSUE #425: Incorrectly constructed diagnostic
When parsing
```mlir
    "pdl_interp.is_not_null"(%0)[^bb2, ^bb1] : (!pdl.operation) -> ()
```
in MLIR mode, with the following definitions:
```py
@irdl_attr_definition
class OperationType(ParametrizedAttribute):
    name = "pdl.operation"
```
and
```py
@irdl_op_definition
class PdlInterpIsNotNull(Operation):
    name = "pdl_interp.is_not_null"
    value: Operand
```

I get a very weird error message that looks a lot like a type error bug in xDSL:
```
xdsl.utils.exceptions.ParseError: test_pdl.mlir:6:68
    "pdl_interp.is_not_null"(%0)[^bb2, ^bb1] : (!pdl.operation) -> ()
                                                                    ^
                                                                    Unexpected exception: '^bb2'
```

Am I defining successors in `PdlInterpIsNotNull` incorrectly? In any case, that does look like an intended error message.

### PR DESCRIPTION
**Pull request by math-fehr**
Fix #425
The issue was that in the new parser, the default parser for parametrized attributes would allow parameters without brackets.

### CODE REVIEW

**Review by AntonLydike — APPROVED** [review]
I'm not sure why we chose to allow parametrized attributes without parameters, as that seems to me like a contradiction in and of itself, but I guess that's just a thing in xDSL/MLIR. Thanks for the fix!

**Comment by math-fehr** [comment]
So the reasonning is these attributes are just attributes with no parameters. The reason why we use `ParametrizedAttribute` and not another option is to not have a third type of attribute, and also since technically this is parametrized, just by no parameters.

**Comment by AntonLydike** [comment]
I guess it actually does make sense! Putting it like that cleared up a lot for me! Thanks!

**Comment by Moxinilian** [comment]
For what it's worth, I believe this fixes the issue I told you about in private but not #425.

**Pull request merged**
