### PR TITLE
core: Switch to ClassVar names in `Operation`, `ModulePass` and `Attribute`

### PR DESCRIPTION
**Pull request by TaoBi22**
As discussed in #750, this updates the names of `Operation`, `ModulePass` and `Attribute` to be `ClassVar`s. This requires some changes to the type hints in dialect definitions, which are also made in this PR.

### CODE REVIEW

**Comment by superlopuh** [comment]
Could you please migrate the tests and Toy dialect, also?

**Review by superlopuh — CHANGES_REQUESTED** [review]
Thank you for doing this, just needs a few more dialects, running `pyright` in the terminal should guide you to the remaining failures

**Review by AntonLydike — APPROVED** [review]
LGTM, just look out for the missed cases in `docs/`

**Comment by TaoBi22** [comment]
@superlopuh @AntonLydike thanks for the catches! Looks like I was just running the wrong pyright hook. We're working on the failing tests :)

**Review by superlopuh — APPROVED** [review]

**Review by superlopuh — APPROVED** [review]

**Review by AntonLydike — APPROVED** [review]

**Comment by math-fehr** [comment]
Arg, everything is good, but the problem is that in the meantime people added more operations!
Could you just fix these ones, and I'll merge this asap?

**Pull request merged**
