### PR TITLE
minor: don't backtrack when trying to parse characters

### PR DESCRIPTION
**Pull request by superlopuh**
I've found that this is often too granular to be super useful when looking at the backtraces. Do you think it would be ok to remove? @AntonLydike , I remember you saying that you might remove backtracking in the medium term, I thought I'd propose removing this part now.

### CODE REVIEW

**Review by math-fehr — APPROVED** [review]
Looks good to me, I don't understand why we should backtrack here!
Note that I would like to remove backtrack completely (or at least the message it generates).

**Comment by math-fehr** [comment]
I would wait for Anton to respond though.

**Review by AntonLydike — APPROVED** [review]
LGTM

**Comment by AntonLydike** [comment]
Yeah, I agree that we should remove backtracking. It really shouldn't be needed, `mlir` should be `LL(1)` in almost all cases, and the custom parsers are usually also quite sane.

**Pull request merged**
