### PR TITLE
misc: update precommit black version

### PR DESCRIPTION
**Pull request by superlopuh**
Turns out we're pretty far behind, so everyone creating new venvs and using black to auto-format in VSCode is introducing slightly incompatible formatting.

### CODE REVIEW

**Review by math-fehr — APPROVED** [review]
I don't like the ugly type syntax, sad they went in that direction but I understand it

**Comment by superlopuh** [comment]
We seem to have bad luck with types these days :)

**Comment by superlopuh** [comment]
Probably with a trick similar to the pyright one

**Comment by superlopuh** [comment]
#2292

**Pull request merged**
