### PR TITLE
dialects: add missing init to riscv.NullaryOperation

### PR DESCRIPTION
**Pull request by superlopuh**

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
Why is this needed? Do any tests break without?

**Comment by superlopuh** [comment]
Because we don't want users to provide any parameters to init, that are currently available

**Comment by superlopuh** [comment]
`IRDLOperation.__init__` allows passing operands/regions etc

**Review by nazavode — APPROVED** [review]

**Comment by superlopuh** [comment]
it's redefining init that prevents this

**Comment by superlopuh** [comment]
That way there's a new init function that doesn't take the parameters of its superclass, so they're not suggestions in the autocomplete

**Pull request merged**
