### PR TITLE
core: make walk an iterator instead of passing function

### PR DESCRIPTION
**Pull request by superlopuh**
Pythonic coroutines 🐍

### CODE REVIEW

**Comment by AntonLydike** [comment]
I wonder if we have some benchmarks for this, not that I'm concerned, but rather intrigues what version would be faster... function calls are expensive, and this minimizes them, right?

**Comment by AntonLydike** [comment]
A super contrived example I benchmarked (not actually xDSL nodes) results in:

```
iter took 55.36897626200516 seconds
cb   took 58.73039559400058 seconds
```

**Review by AntonLydike — APPROVED** [review]
I really like this change!

**Review by tobiasgrosser — APPROVED** [review]

**Review by math-fehr — APPROVED** [review]
Yep, that looks much better now!

**Pull request merged**
