### PR TITLE
dependencies: update ruff-pre-commit to v0.6.0

### PR DESCRIPTION
**Pull request by superlopuh**
bleep bloop

### CODE REVIEW

**Review by alexarice — COMMENTED** [review]
I expect this comes as no surprise but this is a breaking change on nixos

**Review by alexarice — APPROVED** [review]
Manually updated ruff and this works fine, though would appreciate if the pr could be held for a few days until the ruff update reaches repositories (new version seems barely older than this pr?)

**Comment by superlopuh** [comment]
I'll merge it next week

**Review by PapyChacal — APPROVED** [review]
bleep bleep bloop bleep

**Pull request merged**
