### PR TITLE
compiler: refactor repo hierarchy

### PR DESCRIPTION
**Pull request by georgebisbas**
Open for discussion.
This PR may sound like upsetting things in the repo hierarchy but it is not frightening.

The main change is to avoid the src folder and use directly xdsl folder.
This is used in many big projects in this context and helps build packages for PyPI better.

Please check for proof, other major projects that have a similar structure:

https://github.com/numpy/numpy/tree/main/numpy
https://github.com/tensorflow/tensorflow/tree/master/tensorflow
https://github.com/pytorch/pytorch/tree/master/torch
https://github.com/scikit-learn/scikit-learn/tree/main/sklearn
https://github.com/scipy/scipy/tree/main/scipy

### CODE REVIEW

**Comment by math-fehr** [comment]
Yes, this looks good to me!
Should we merge it now?

**Review by math-fehr — APPROVED** [review]

**Comment by georgebisbas** [comment]
Yes, let's go, please press the button!

**Comment by superlopuh** [comment]
`python -m pytest` works, all good

**Comment by superlopuh** [comment]
Might want to updat ethe readme though

**Comment by georgebisbas** [comment]
@superlopuh how did you install xdsl?

**Comment by superlopuh** [comment]
I didn't, I launch it from the repo

**Pull request merged**
