### PR TITLE
dialects (arith) add fastmath option for float comparisons

### LINKED ISSUE #2725: arith: Missing `fastmath` property on `arith.cmpf`
Similar to many other floating point operations in `arith`, `arith.cmpf` supports specifying relaxations of semantics for code generation and optimizations using the `fastmath` attribute: https://mlir.llvm.org/docs/Dialects/ArithOps/#attributes-2 

This attribute is currently missing from `cmpf` in xDSL making it impossible to import from generic syntax.

### PR DESCRIPTION
**Pull request by knickish**
Add an optional fastmath attribute to `arith.cmpf` and include the attribute while lowering to riscv

Hopefully closes #2725.

### CODE REVIEW

**Comment by superlopuh** [comment]
This is great! Could you please split this into three PRs: arith, riscv, and lowering?

**Comment by superlopuh** [comment]
The code pretty much looks ready to merge, but it would be good to add some filecheck tests for the custom format for each of the dialect PRs.

**Comment by knickish** [comment]
@superlopuh I will attempt to split it up. Can you explain `filecheck tests for the custom format for each of the dialect PRs` a bit more though? I'm not sure exactly what that means

**Comment by knickish** [comment]
Alright, Have it split up into #3275, #3726, and #3277. I think I figured out what you meant by the dialect tests, and each of the PRs has an associated filecheck test now.

**Pull request closed without merging**
