### PR TITLE
core: Fix parsing for hex denseAttrs

### PR DESCRIPTION
**Pull request by vinayakdsci**
Fixes https://github.com/xdslproject/xdsl/issues/2876.

The original parsing implementation for hex denseAttrs uses format strings in `struct.unpack_from()`, but the format strings actually do not include the count of the chunks contained in the bytes list.

This patch fixes this behavior by embedding the number of chunks in the respective format string.

### CODE REVIEW

**Comment by vinayakdsci** [comment]
cc @superlopuh @gabrielrodcanal @JosseVanDelm.

**Comment by superlopuh** [comment]
Could you please add a unit test that fails before your patch, and works after?

**Comment by vinayakdsci** [comment]
@superlopuh Added.

**Review by superlopuh — APPROVED** [review]
Very nice, thank you!

**Comment by JosseVanDelm** [comment]
Thanks @vinayakdsci !

**Pull request merged**
