### PR TITLE
Use walrus operator for readability. PEP 572

### PR DESCRIPTION
**Pull request by K-W-Li**
Also use the obtained ssa_value instead of getting from dict again.

### CODE REVIEW

**Comment by K-W-Li** [comment]
It seems I don't have sufficient permission to directly commit changes following the corresponding PR.

**Comment by K-W-Li** [comment]
I suppose this should be mergeable as shown bellow? Or maby I misunderstanding somethings?
image
I remember checkout on branch [missing_ssa_val_print](https://github.com/xdslproject/xdsl/tree/missing_ssa_val_print) before modifying.

**Comment by webmiche** [comment]
My problem is that one of your commits (the second one) is a merge commit. I would prefer to not have this kind of commits in our history. Hmm, the PR earlier was better in terms of commits, but had the wrong base branch selected. If you could reopen that one and select my branch as the base, I think I can merge it.

**Comment by math-fehr** [comment]
@K-W-Li, you should have write access to the repo, maybe check your emails for the invitation?
Otherwise, @webmiche, you should be able to merge and squash it directly, and I guess it will remove the merge commit!

**Comment by K-W-Li** [comment]
Successfully commit at #119. Close this one.

**Pull request closed without merging**
