### PR TITLE
dialects: Missing math operations

### PR DESCRIPTION
**Pull request by mesham**
Missing operations in the math dialect which now makes this complete wrt the MLIR counterpart. This is experimental (so no tests etc). Therefore when it passes the build tests I will merge it straight in

### CODE REVIEW

**Review by georgebisbas — COMMENTED** [review]
Great additions Nick, I wonder why would we not write tests?

**Comment by meshtag** [comment]
If this is required urgently in the codebase, then perhaps we can create a feature request to add tests later (given that it is in the experimental folder)?

**Comment by mesham** [comment]
> Great additions Nick, I wonder why would we not write tests?

Feel free to write tests, they are required to move this from experimental - I just don't have time to do this with all my PSyclone integration work being the priority.

**Comment by PapyChacal** [comment]
After similar discussions, I started putting #TODO in the experimental codebase, as a marker for things to check before going out of experimental.
Just saying this to spread the convention; having unit tests at all seems big enough for us to remember anyway

**Comment by mesham** [comment]
> If this is required urgently in the codebase, then perhaps we can create a feature request to add tests later (given that it is in the experimental folder)?

I don't think we need to? The point of experimental (as far as I am aware) is to allow these lesser mature things in, which can be added to (i.e. with tests) later on?

**Pull request merged**
