### PR TITLE
core: add IRDLOperation with init that uses same logic as build

### PR DESCRIPTION
**Pull request by superlopuh**
Got inspired to explore this route, was surprisingly fast to get to a working solution, so I thought I'd push a PR to discuss pros and cons vs other potential approaches. I migrated the Toy dialect, and it does look a little neater now. I'd love to one day get to automatically generated inits but this approach would not make it any harder to get there, I don't think.

### CODE REVIEW

**Comment by math-fehr** [comment]
Have you checked with @PapyChacal?
The current design objective is to remove the `build` functions from `Operation` entirely, as they do not make sense, since `Variadic` are concepts that only exist in IRDL.

I'm not sure I like the `OperationModel` here. Why do we want to expose this, as it is only used by the `builder?
I feel that otherwise, you get a relatively similar design, I just think we should decouple things between `Operation` and `IRDLOperation`, which Emilien is currently implementing.

**Comment by superlopuh** [comment]
Yeah hopefully we'll get some time to chat about this tomorrow, I've been following his PRs. I thought I'd see if there's a way to adopt the new way of doing things incrementally, and this seems like a potentially promising way of doing it.

**Comment by superlopuh** [comment]
The `OperationModel` is just a dummy container for all the fields, the alternative is to return a massive tuple, or a `TypedDict`, and this seems marginally more readable.

**Comment by math-fehr** [comment]
> The `OperationModel` is just a dummy container for all the fields, the alternative is to return a massive tuple, or a `TypedDict`, and this seems marginally more readable.

There is another alternative that I discussed with Emilien.
Instead, we can have a `__init_build__`, which does the builder logic, and set the fields.
Alternatively, we could just define the `builder` logic in the `__init__` of `IRDLOperation`, and let users choose between calling this `__init__` or the `Operation` one.

**Comment by superlopuh** [comment]
Yep all good options, I'm happy with either.

**Comment by math-fehr** [comment]
I just think that it's better to discuss these things with the person that currently implements them beforehand.
Otherwise we just end up duplicating completely the work, and I'm not sure it's very productive :/

**Comment by superlopuh** [comment]
I'm happy to throw away my code, I find it much easier to understand the issues when I get my hands dirty, there were a bunch of things that surprised me while I was playing around with this. Don't feel like I wasted the time at all. One of the things that I hadn't realised is that it's the `dataclass` generated init that calls the `__post_init__`, it's not a Python thing.

**Comment by math-fehr** [comment]
> I'm happy to throw away my code, I find it much easier to understand the issues when I get my hands dirty, there were a bunch of things that surprised me while I was playing around with this. Don't feel like I wasted the time at all. One of the things that I hadn't realised is that it's the `dataclass` generated init that calls the `__post_init__`, it's not a Python thing.

Okay, my bad, I see your reasoning!
I'm just scared that we lose too much time on these things, but since this is a complex issue it makes sense!

**Comment by superlopuh** [comment]
You're right that it's not efficient for us not to coordinate at all and all work on the same thing. I think Emilien and I are generally interested in the same sort of fixups so we've had that sort of work duplication before :) I am conscious of it and have been communicating with people before I spend too much time on things that are likely to overlap

**Comment by PapyChacal** [comment]
So I discussed with @superlopuh (please correct me if I'm wrong in the following! I don't want to add confusion) And to sum it up, he is okay with my PR as well, and meant this PR as another proposition, more incremental in some way, compared to my "Rip the band-aid" approach, touching basically all the dialects and docs at once.
I had a similar feeling on doing things twice, but I would argue here it might have been be valuable. We both wanted to understand the current state of some complicated parts of the code, and I think we both did!

I think the sensible thing to do now is to focus the discussion on #722: If we agree on it, we can go for my `__init__` PR. If people prefer a more progressive approach, we can go for this one!

**Comment by webmiche** [comment]
I prefer the other approach of the other PR. It feels to me like we should try to separate IRDL and the IR structures as much as possible, to allow implementing other IRDL-like things in the future. Also, it just feels like a cleaner code structure, simplifying testing and analysis...

**Comment by superlopuh** [comment]
Closing in favour of #700

**Pull request closed without merging**
