### PR TITLE
core: (rewriting) Fix recursive type conversion in block arguments for nested regions

### LINKED ISSUE #2857: Type Conversion of function arguments
I am unsure if this is intended behavior or I am doing something incorrectly, but when I try using a TypeConversionPattern on the arguments of a FuncOp, the argument types do not change even with the recursive flag set to True.

An example:  
```python
from xdsl.dialects.func import Func
from xdsl.dialects.builtin import (
    Builtin,
    IndexType,
    IntegerType,
)
from xdsl.parser import Parser
from xdsl.pattern_rewriter import (
    PatternRewriteWalker,
    TypeConversionPattern,
    attr_type_rewrite_pattern,
)
from xdsl.context import MLContext


prog = """\
"builtin.module"() ({
  "func.func"() <{function_type = (memref<2x4xui16>, memref<2x3xui8>) -> (), sym_name = "main", sym_visibility = "private"}> ({
  ^bb0(%arg0: memref<2x4xui16>, %arg1: memref<2x3xui8>):
    "func.return"() : () -> ()
  }) : () -> ()
}) : () -> ()
"""

ctx = MLContext()
ctx.load_dialect(Builtin)
ctx.load_dialect(Func)
parser = Parser(ctx, prog)
module = parser.parse_module()


class Rewrite(TypeConversionPattern):
    @attr_type_rewrite_pattern
    def convert_type(self, typ: IntegerType) -> IndexType:
        return IndexType()


PatternRewriteWalker(Rewrite(recursive=True), apply_recursively=True).rewrite_module(
    module
)
```

The output of the above code snippet is:
```mlir
builtin.module {
  func.func private @main(%arg0 : memref<2x4xui16>, %arg1 : memref<2x3xui8>) {
    func.return
  }
}
```
while I expected:
```mlir
builtin.module {
  func.func private @main(%arg0 : memref<2x4xindex>, %arg1 : memref<2x3xindex>) {
    func.return
  }
}
```

### PR DESCRIPTION
**Pull request by webmiche**
closes #2857 

Solves the issue mentioned there and adds the reported testcase as a regression test.

Before, this was actually quite broken as not applying the recursive rewrite, but the normal rewrite, to the region would actually mean that the produced func_op did not even verify (the `function_type` attribute got rewritten properly, whereas the entry_block args would still have the old type). 

The reason why the old type was being printed is that the `print_func_op_like`-utility function defaults to printing the entry_block arguments in some cases.

### CODE REVIEW

**Comment by webmiche** [comment]
@francescodaghero feel free to also comment/leave a review :)

**Review by superlopuh — APPROVED** [review]

**Comment by webmiche** [comment]
@superlopuh do you think we can merge this without @PapyChacal s approval? It seems like fairly obvious fix to me, but I am not very deep in the intricacies of the TypeConversion stuff.

**Comment by webmiche** [comment]
Hmm, yeah fair enough. I am honestly not sure what we want this API to look like exactly, but your change sounds reasonable.

**Comment by webmiche** [comment]
I will wait for the CI to pass and then merge.

**Pull request merged**
