### PR TITLE
dialects: Replacing get with init in mpi dialect and respective places

### PR DESCRIPTION
**Pull request by ShaolunWang**
Replacing `get` method with `init` in mpi dialect and respective places, `get` methods in mpi diaclect are marked as deprecated.

### CODE REVIEW

**Review by superlopuh — APPROVED** [review]
thank you

**Comment by AntonLydike** [comment]
Thanks! Do you want this PR assigned to yourself?

**Review by AntonLydike — APPROVED** [review]
Thanks for this!

**Comment by ShaolunWang** [comment]
> Thanks! Do you want this PR assigned to yourself?
sure

**Review by compor — APPROVED** [review]

**Pull request merged**
