### PR TITLE
misc: Add coverage generation rules to Makefile

### PR DESCRIPTION
**Pull request by compor**
Adds coverage generation and report (html and markdown) rules to Makefile.

### CODE REVIEW

**Review by webmiche — APPROVED** [review]

**Review by superlopuh — CHANGES_REQUESTED** [review]
Could you please replicate the behaviour of `ci-mlir.yml` and check that the coverage report is identical to the CI?

**Comment by compor** [comment]
I replicated the coverage behaviour of the CI and also allow optional execution of coverage in filechecks if `mlir-opt` is not in the `PATH` env variable.

**Comment by math-fehr** [comment]
Just something I don't understand, is there a reason why we don't want to try the coverage when `mlir-opt` is not in the PATH? AFAIK, it should still work, right? It will just not output the `mlir-opt` tests, but that should be fine?

**Comment by compor** [comment]
> Just something I don't understand, is there a reason why we don't want to try the coverage when `mlir-opt` is not in the PATH? AFAIK, it should still work, right? It will just not output the `mlir-opt` tests, but that should be fine?

It does work indeed.
I sort of assumed from the prior comments that we don't want coverage there if `mlir-opt` is not available.
I'll amend.

**Review by math-fehr — APPROVED** [review]
Looks good to me!

**Review by superlopuh — APPROVED** [review]
thank you!

**Pull request merged**
