### PR TITLE
dialects: Add the basic concept of compilation targets

### PR DESCRIPTION
**Pull request by AntonLydike**
This is the start of my crusade to get a concept of ABI, targets, etc into the RISC-V backend.

I also moved this into a riscv folder, because I didn't know where to best place this. I feel that we should probably bundle all the risc-v stuff into a single submodule.

This is still missing all the linker stuff. Although I'm unsure if we even want that in here, as we may or may not want to do any linking.

This is still not quite ready, I have an error in the `march` extension formatting. But that's not really relevant to get the discussion going I feel.

I don't know if the codebase actually *needs* this, but I feel we need to discuss this a bit before we continue with the current path. Opinions welcome!

*Quick disclaimer:* I feel that time spent on this wasn't wasted as it helped me refresh and improve my knowledge of what is API/ABI/march etc. greatly, which will come in useful further down the line!

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
Hi @AntonLydike, thank you for bringing this up. I personally would have loved to avoid this topic until we have a need for multiple ABIs. ABIs are complex and I feel it is more honest to just hardcode one than to generalize early. If we want to add full ABI support, I feel this requires detailed and costly discussions that maybe we can avoid for now. Just my 2 cents.

**Comment by AntonLydike** [comment]
> ABIs are complex and I feel it is more honest to just hardcode one than to generalize early. If we want to add full ABI support, I feel this requires detailed and costly discussions that maybe we can avoid for now. Just my 2 cents.

I agree with that, I don't think we want to support multiple ABIs. I'm fine with saying that we do `-mabi=ilp32f -march=RV32IMAFZifencei -mcmodel=medany` for now. We should just know what it means, if that makes sense?

**Comment by tobiasgrosser** [comment]
That makes a lot of sense. Which ABI does riscemu support?

Also, even there I am not sure how much of the ABI do we want to cover. Do we want full support for passing C structs by value and stuff with vector registers, or is there a minimal subset (e.g., only scalars and pointers), that we could use?

**Review by nazavode — APPROVED** [review]
While I agree with @tobiasgrosser that ABIs are gates to hell, this is the most concise and clear definition of a platform I've ever seen tho. If this becomes useful for #995 and related efforts, I would rather have this merged just to provide some details and constants collected in a single place.

**Comment by tobiasgrosser** [comment]
Just to clarify. I am happy to have constants and Abi Informationen becoming clearly marked. I feel doing this (maybe with this patch) might help also as documentation on the ABIs that we currently focus on.

**Review by tobiasgrosser — APPROVED** [review]
Happy to see this merged.

**Comment by superlopuh** [comment]
What's the latest on this? Do we want to merge it, close it, keep it open? One thing I would change is that we have a top-level `backend` folder with riscv in it, so maybe that's a better place for all this. Some tests would be good also

**Review by superlopuh — APPROVED** [review]
thank you

**Pull request merged**
