### PR TITLE
Test cleanup

### PR DESCRIPTION
**Pull request by Dinistro**
This cleans up most of the tests by replacing them with filecheck tests. 
I was not yet able to move the mlir_converter test, as the converter itself is broken for the CF dialect.

### CODE REVIEW

**Review by webmiche — APPROVED** [review]
LGTM. I think we could keep the names of the files as `.test` since they are really test files and not pure `.xdsl` files, but I am fine with the way it is now.

**Comment by Dinistro** [comment]
I renamed them to `.xdsl` such that the opt tool can determine the file type easily.

**Comment by webmiche** [comment]
Can you update the opt tool then such that it does not handle `.test` the same as `.xdsl`?

**Comment by Dinistro** [comment]
> Can you update the opt tool then such that it does not handle `.test` the same as `.xdsl`?

Good point, done

**Pull request merged**
