### PR TITLE
dialects: (csl) handle negative-valued task ID representation

### PR DESCRIPTION
**Pull request by superlopuh**
i6 and friends are signless, meaning that they are bitpatterns that don't have an inherent value. When printing CSL, we currently take the raw data of the IntegerAttr, but it seems like that's not valid for task identifiers, which are positive. This PR changes the printer to always print the unsigned version of the number, and adds a test case to the CSL filecheck.

### CODE REVIEW

**Comment by dk949** [comment]
I think this makes sense, even if it is really odd to see a negative task ID in the IR.

As a sidenote, it would've probably been better to have made this an `i16` and dealt with the range in the `verify`

**Comment by superlopuh** [comment]
There are probably a few things to do, and making it an unsigned integer is also an option, especially if you'll not do any more arithmetic with it once you pin it down. If you'd like, I can do that in this PR instead?

**Comment by superlopuh** [comment]
I decided to try it out, happy to revert to previous version if you'd like to keep the IDs signless.

**Review by n-io — APPROVED** [review]
Looks good, @dk949 ?

**Review by dk949 — APPROVED** [review]
I like this, it exactly expresses the constraints on these values in the types.

**Review by emmau678 — APPROVED** [review]

**Pull request merged**
