### PR TITLE
dialects: Fix affine.ParallelOp boundsGroup checks.

### PR DESCRIPTION
**Pull request by PapyChacal**
The current (my :sweat_smile:) verifier of `affine.parallel` is off.
boundsGroups work like operandSegmentSizes; it contains the lengths of each group.
The current verifier assumes they work like mappings from each bound to its group.

### CODE REVIEW

**Review by georgebisbas — COMMENTED** [review]
How did you find it is off? Add a test? ;-)

**Comment by PapyChacal** [comment]
> How did you find it is off? Add a test? ;-)

Through errors on an xDSL+MLIR flow I'm working on; will try and add a test sure!

**Comment by superlopuh** [comment]
@PapyChacal, any progress on this?

**Comment by PapyChacal** [comment]
> @PapyChacal, any progress on this?

Yep :angel:

**Pull request merged**
