### PR TITLE
CI: Upload the line by line coverage

### PR DESCRIPTION
**Pull request by webmiche**

### CODE REVIEW

**Comment by webmiche** [comment]
@georgebisbas On the most recent push, I can once again inspect the line by line coverage. Though there is an error that there were multiple uploads on the current base branch. I am inspecting that atm.

**Comment by webmiche** [comment]
I am confused. It really only seems to be [this commit](https://github.com/xdslproject/xdsl/commit/33bf11e0d3488597d0865fc623a724e024f5b755) that had multiple reports uploaded. The ones before it are fine...

**Review by georgebisbas — APPROVED** [review]

**Comment by math-fehr** [comment]
Do you have a link to codecov where you can see the lines?
Otherwise, if this is ready to merge, we can merge it

**Comment by webmiche** [comment]
I think the current base was weird, let's see if it works now. If so, I can post the link here :)

**Comment by webmiche** [comment]
Looks fixed to me: https://app.codecov.io/gh/xdslproject/xdsl/blob/main/xdsl/ir.py

@math-fehr @georgebisbas

**Pull request merged**
