### PR TITLE
interactive: do not auto_expand passes_list

### PR DESCRIPTION
**Pull request by alexarice**
I was really struggling to debug this, but from what I can understand the `child_pass_pipeline` was ending up with duplicate passes because `self.pass_pipeline` shouldn't have been added. 
I'm not 100% this is the correct fix as I didn't manage to work out what everything did and why.

### CODE REVIEW

**Comment by alexarice** [comment]
I'm now pretty sure this change is wrong, I'm going to try to properly figure out what's going on

**Comment by compor** [comment]
@alexarice how do you trigger the crash?

**Comment by alexarice** [comment]
1. run `xdsl-gui`
2. Click dropdown in pass list
3. scroll to bottom
4. click the individual pass

**Comment by alexarice** [comment]
I think I've figured it out. In `expand_tree_node` we try to get the next passes that can be applied, to do this we need the pass list to get to this node of the tree which is gotten by appending:
- `self.pass_pipeline`: The selected passes
- `root_to_child_pass_list`: Passes from the root of the tree (exclusive) to the node to be expanded (exclusive)
- The expanded node
I believe the issue is that when the `root_to_child_pass_list` is empty, the "expanded node" is already in the pass pipeline and gets duplicated

**Comment by compor** [comment]
Very plausible, and that point caught my attention as suspicious.
It would be good to have someway to test this, but I can't see how to do so easily without refactoring this bit.

**Comment by alexarice** [comment]
Completely different fix: the passes_list automatically expanded nodes that were selected. As selection is overriden to reset the tree I think this was breaking stuff.

**Comment by alexarice** [comment]
I still haven't quite got my head around the tree constructions above, but with `auto_expand = False` all the problems go away. I have no idea how to test this (I guess a test that "clicks on" some individual rewrites might be a good idea)

**Comment by compor** [comment]
yeah, where "clicks on" would be somehow disentangled from the UI functionality in a typical MVC, so we could actually test it?

I'll be OK accepting this if you open an issue tracking the suggested improvement, so we can move on.

**Review by compor — APPROVED** [review]

**Comment by compor** [comment]
> (I guess a test that "clicks on" some individual rewrites might be a good idea)

**Comment by superlopuh** [comment]
So you're suggesting skipping adding a unit test?

**Comment by alexarice** [comment]
I'm doing the unit test now

**Comment by compor** [comment]
@alexarice I wasn't sure by your phrasing how laborious that was; if there is a unit test, I'll take it.

**Comment by alexarice** [comment]
I've added a test that selects some individual rewrites. It's not the cleanest but it crashes without this change and works with it

**Review by compor — APPROVED** [review]
laborious, thanks

**Review by superlopuh — APPROVED** [review]
Amazing, thank you

**Pull request merged**
