### PR TITLE
interpreters: (irdl) generate better op name

### LINKED ISSUE #3527: misc: generate class names that satisfy our coding convention in irdl.mlir file loading
Currently, the cmath dialect, defined as an irdl file, is imported into Python with the class names matching the operation names. We should make using irdl files as smooth a process as possible, and matching coding conventions is an important aspect of this. So we should import `cmath.norm` not as `class norm(IRDLOperation)`, but `class NormOp(IRDLOperation)`.

### PR DESCRIPTION
**Pull request by alexarice**
Fixes #3527
Stacked but can be unstacked

### CODE REVIEW

**Comment by superlopuh** [comment]
Oh and let's fix the test also to remove the cmath check

**Comment by alexarice** [comment]
> Let's unstack

Might be easier just to deal with one PR at a time on second thoughts

**Comment by superlopuh** [comment]
Your call

**Review by math-fehr — APPROVED** [review]
Nice!
Actually I'm wondering if we should not move `get_op_name` to  `OperationOp` directly?
Just to make it more easily discoverable, since it is only a few lines of code anyway

**Comment by superlopuh** [comment]
I like that a lot, although in that case I'd call it something like `get_py_class_name`

**Comment by superlopuh** [comment]
It definitely seems easier to unstack at this point, as the location and name of the op may need to be changed for both PRs...

**Comment by alexarice** [comment]
I'm not sure I understand unstacking. To me it makes sense to fix up the other PR, get it merged, then rebase/remake this one

**Comment by alexarice** [comment]
By unstack did you mean make the 2 PRs into 1 PR?

**Comment by superlopuh** [comment]
Yep sorry I thought that's what you meant.

**Comment by alexarice** [comment]
For some reason I thought you meant to make 2 completely separate PRs which both add the new function separately, sorry again for the confusion

**Comment by alexarice** [comment]
The diff here isn't correct, I'll sort it out

**Comment by superlopuh** [comment]
That's my bad for assuming what you meant!

**Comment by alexarice** [comment]
Diff looks better now

**Review by superlopuh — APPROVED** [review]

**Pull request merged**
