### PR TITLE
python: Use f-string

### PR DESCRIPTION
**Pull request by kingiler**
- python: Use f-string instead of .format or %

### CODE REVIEW

**Review by math-fehr — APPROVED** [review]
:+1:

**Comment by superlopuh** [comment]
This broke pyright in main... Can you please avoid merging without the CI running successfully? The CI won't run by default with PRs from forks, so probably easier to use the xDSL repo to fix

**Comment by compor** [comment]
@kingiler can you please refrain from merging with just a single approval?
there is no rush, especially for these kind of changes.

**Comment by kingiler** [comment]
I can't see pyright is broken? Merging won't be successful without tasks successfully checked.

------- Original Message -------

**Comment by superlopuh** [comment]
Yeah I don't know why my VSCode was complaining. Maybe I was on a different version of pyright or pylance. It no longer complains

**Pull request merged**
